<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><div><h2 class="text-xl font-semibold">{{ $agent->name }} — Commission history</h2><div class="text-sm font-semibold text-gray-500">Referral # {{ $agent->referral_code }}</div></div><a href="{{ route('agents.index') }}" class="text-indigo-600">← Agents</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl px-4 space-y-5">
        @if(session('success'))<div class="rounded-lg bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-lg bg-red-100 p-4 text-red-800">{{ $errors->first() }}</div>@endif
        <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-xl bg-white p-5 shadow"><div class="text-sm text-gray-500">Payable commission</div><div class="text-2xl font-bold text-green-700">Rs {{ number_format($summary->payable,2) }}</div></div><div class="rounded-xl bg-white p-5 shadow"><div class="text-sm text-gray-500">Reversed commission</div><div class="text-2xl font-bold text-red-700">Rs {{ number_format($summary->reversed,2) }}</div></div><div class="rounded-xl bg-white p-5 shadow"><div class="text-sm text-gray-500">Lifetime generated</div><div class="text-2xl font-bold">Rs {{ number_format($summary->lifetime,2) }}</div></div></div>
        <div class="grid gap-5 lg:grid-cols-2"><div class="rounded-xl bg-white p-6 shadow"><h3 class="text-lg font-bold">Pay agent commission</h3><p class="mt-1 text-sm text-gray-500">This records the agent's complete current payable balance as paid.</p>@if((float)$summary->payable>0)<div class="mt-4 rounded-xl bg-green-50 p-4"><div class="text-xs font-semibold uppercase text-green-600">Amount to pay</div><div class="mt-1 text-3xl font-black text-green-800">Rs {{ number_format($summary->payable,2) }}</div></div><form method="POST" action="{{ route('agents.payouts.store',$agent) }}" class="mt-4 grid gap-4 sm:grid-cols-2">@csrf<label class="text-sm font-medium">Payment method<select name="payment_method" required class="mt-1 w-full rounded-md border-gray-300">@foreach(['bank_transfer','cheque','easypaisa','jazzcash','crypto'] as $method)<option value="{{ $method }}">{{ ucwords(str_replace('_',' ',$method)) }}</option>@endforeach</select></label><label class="text-sm font-medium">Reference<input name="transaction_reference" maxlength="100" class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium sm:col-span-2">Notes<textarea name="notes" rows="2" class="mt-1 w-full rounded-md border-gray-300"></textarea></label><button onclick="return confirm('Record full commission payout of Rs {{ number_format($summary->payable,2) }}?')" class="rounded-md bg-green-600 px-5 py-2.5 font-bold text-white sm:col-span-2">Pay full payable commission</button></form>@else<div class="mt-5 rounded-xl bg-gray-50 p-6 text-center text-sm text-gray-500">No earned commission is currently payable.</div>@endif</div><div class="overflow-hidden rounded-xl bg-white shadow"><div class="border-b p-6"><h3 class="text-lg font-bold">Payout history</h3><p class="text-sm text-gray-500">Completed payments made to this agent</p></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50 text-left text-gray-500"><tr><th class="p-4">Payout</th><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>@forelse($payouts as $payout)<tr class="border-t"><td class="p-4 font-mono text-xs font-bold">{{ $payout->payout_number }}</td><td>{{ $payout->paid_at->format('d M Y') }}</td><td>{{ ucwords(str_replace('_',' ',$payout->payment_method)) }}</td><td>{{ $payout->transaction_reference??'—' }}</td><td class="font-bold text-green-700">Rs {{ number_format($payout->amount,2) }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-gray-500">No commission payouts recorded.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="grid gap-5 lg:grid-cols-2">
            <div class="rounded-xl bg-white p-6 shadow"><div class="mb-5"><h3 class="text-lg font-bold">Sponsor hierarchy</h3><p class="text-sm text-gray-500">Who this agent reports to, up to 3 sponsors.</p></div><div class="space-y-3"><div class="rounded-lg border-2 border-indigo-500 bg-indigo-50 p-4"><div class="text-xs font-semibold uppercase text-indigo-600">Selected agent</div><div class="font-bold">{{ $agent->name }}</div></div>@forelse($upline as $node)<div class="ms-6 border-s-2 border-gray-300 ps-5"><div class="mb-2 text-xl text-gray-400">↑</div><div class="rounded-lg border p-4"><div class="text-xs font-semibold uppercase text-gray-500">Sponsor {{ $node['level'] }}</div><div class="font-bold">{{ $node['user']->name }}</div><div class="text-xs text-gray-500">{{ $node['user']->role }} · {{ $node['user']->status?'Active':'Inactive' }}</div><div class="mt-1 text-sm text-green-700">Payable: Rs {{ number_format($node['user']->payable_commission??0,2) }}</div></div></div>@empty<div class="text-sm text-gray-500">No sponsor assigned.</div>@endforelse</div></div>
            <div class="rounded-xl bg-white p-6 shadow"><h3 class="mb-5 text-lg font-bold">Three-level downline</h3>@forelse($downline as $node) @include('agents._tree_node',['node'=>$node]) @empty<div class="rounded-lg bg-gray-50 p-6 text-center text-sm text-gray-500">No agents in this downline.</div>@endforelse</div>
        </div>
        <form method="GET" class="grid gap-3 rounded-xl bg-white p-4 shadow sm:grid-cols-3"><label class="text-sm font-medium">Status<select name="status" class="mt-1 w-full rounded-md border-gray-300"><option value="">All statuses</option><option value="earned" @selected(request('status')==='earned')>Earned / payable</option><option value="paid" @selected(request('status')==='paid')>Paid out</option><option value="reversed" @selected(request('status')==='reversed')>Reversed</option></select></label><label class="text-sm font-medium">Commission level<select name="level" class="mt-1 w-full rounded-md border-gray-300"><option value="">All levels</option>@foreach([1,2,3] as $level)<option value="{{ $level }}" @selected(request('level')==$level)>Level {{ $level }}</option>@endforeach</select></label><div class="flex items-end gap-2"><button class="rounded bg-indigo-600 px-5 py-2.5 font-semibold text-white">Filter</button><a href="{{ route('agents.show',$agent) }}" class="rounded border px-4 py-2.5">Clear</a></div></form>
        <div class="overflow-x-auto rounded-xl bg-white shadow"><table class="w-full text-sm"><thead class="bg-gray-50 text-left text-gray-500"><tr><th class="p-4">Date / Receipt</th><th>Customer</th><th>Booking</th><th>Project / Package</th><th>Payment</th><th>Level</th><th>Rate</th><th>Commission</th><th>Status</th></tr></thead><tbody>
        @forelse($commissions as $commission)<tr class="border-t"><td class="p-4"><div>{{ $commission->created_at->format('d M Y, h:i A') }}</div><a href="{{ route('payments.edit',$commission->payment) }}" class="text-xs text-indigo-600">{{ $commission->payment->receipt_number }}</a></td><td>{{ $commission->booking->customer->name }}</td><td><a href="{{ route('bookings.show',$commission->booking) }}" class="text-indigo-600">{{ $commission->booking->booking_number }}</a></td><td>{{ $commission->booking->project->name }}<div class="text-xs text-gray-500">{{ $commission->booking->package->name }}</div></td><td>Rs {{ number_format($commission->payment->amount,2) }}</td><td>Level {{ $commission->level }}</td><td>{{ number_format($commission->percentage,2) }}%</td><td class="font-bold text-green-700">Rs {{ number_format($commission->amount,2) }}</td><td><span class="rounded-full px-2 py-1 {{ $commission->status==='earned'?'bg-green-100 text-green-700':($commission->status==='paid'?'bg-blue-100 text-blue-700':'bg-red-100 text-red-700') }}">{{ $commission->status==='paid'?'Paid out':ucfirst($commission->status) }}</span></td></tr>
        @empty<tr><td colspan="9" class="p-10 text-center text-gray-500">No commission transactions found.</td></tr>@endforelse</tbody></table></div>{{ $commissions->links() }}
    </div></div>
</x-app-layout>
