<x-app-layout>
    <div class="relative min-h-screen overflow-hidden bg-gradient-to-br from-emerald-50 via-white to-indigo-50 py-6 dark:from-slate-950 dark:via-slate-950 dark:to-emerald-950/30 sm:py-8">
        <div class="pointer-events-none absolute -left-32 top-32 h-96 w-96 rounded-full bg-emerald-200/35 blur-3xl dark:bg-emerald-900/20"></div>
        <div class="pointer-events-none absolute -right-32 top-[34rem] h-96 w-96 rounded-full bg-violet-200/35 blur-3xl dark:bg-violet-900/20"></div>
        <div class="relative w-full space-y-6 px-3 sm:px-5 lg:px-6">
            @if($portalPreview ?? false)<div class="flex flex-col gap-3 rounded-xl border border-emerald-300 bg-emerald-950 px-4 py-3 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between"><div><b class="text-sm">Admin commission preview</b><p class="text-xs text-emerald-200">Viewing {{ $customer->name }}'s commission history in read-only mode.</p></div><div class="flex gap-2"><a href="{{ route('customers.team', $customer) }}" class="rounded-lg bg-emerald-700 px-4 py-2 text-xs font-black text-white">View team</a><a href="{{ route('customers.show', $customer) }}" class="rounded-lg bg-white px-4 py-2 text-xs font-black text-emerald-800">Exit preview</a></div></div>@endif

            <section class="relative isolate overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-emerald-900 to-teal-600 p-6 text-white shadow-2xl shadow-emerald-200/70 dark:shadow-none sm:p-8">
                <div class="absolute -right-20 -top-24 -z-10 h-80 w-80 rounded-full bg-cyan-300/25 blur-3xl"></div>
                <div class="absolute -bottom-28 left-1/3 -z-10 h-64 w-64 rounded-full bg-violet-400/20 blur-3xl"></div>
                <div class="absolute inset-0 -z-10 opacity-[.07]" style="background-image:radial-gradient(circle at 1px 1px,#fff 1px,transparent 0);background-size:23px 23px"></div>
                <div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
                    <div><span class="inline-flex items-center gap-2 rounded-full border border-emerald-200/20 bg-white/10 px-3 py-1 text-[10px] font-black uppercase tracking-[.18em] text-emerald-100"><span class="h-2 w-2 rounded-full bg-emerald-300"></span>Referral earnings</span><span class="sr-only">Commission history</span><h1 class="mt-4 text-3xl font-black tracking-tight sm:text-5xl">Your commission wallet</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-emerald-100">Track every earning generated across your three-level team, from the verified customer payment to its payout status.</p></div>
                    @unless($portalPreview ?? false)<a href="{{ route('customer.withdrawals.index') }}" class="inline-flex w-fit items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-emerald-800 shadow-xl transition hover:-translate-y-0.5 hover:bg-emerald-50">Withdraw commission <span>↗</span></a>@endunless
                </div>
            </section>

            <div class="grid gap-4 sm:grid-cols-3">
                <div class="group relative overflow-hidden rounded-3xl bg-gradient-to-br from-amber-400 to-orange-600 p-5 text-white shadow-xl shadow-amber-200/60 transition hover:-translate-y-1"><div class="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/10"></div><div class="relative flex items-center justify-between"><span class="text-[10px] font-black uppercase tracking-wider text-amber-50">Payable commission</span><span class="grid h-10 w-10 place-items-center rounded-xl bg-white/15 text-lg">↗</span></div><div class="relative mt-5 text-2xl font-black sm:text-3xl">Rs {{ number_format($summary?->payable ?? 0, 2) }}</div><p class="relative mt-1 text-xs text-amber-50">Earned and ready for withdrawal</p></div>
                <div class="group relative overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-500 to-teal-700 p-5 text-white shadow-xl shadow-emerald-200/60 transition hover:-translate-y-1"><div class="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/10"></div><div class="relative flex items-center justify-between"><span class="text-[10px] font-black uppercase tracking-wider text-emerald-50">Paid commission</span><span class="grid h-10 w-10 place-items-center rounded-xl bg-white/15 text-lg">✓</span></div><div class="relative mt-5 text-2xl font-black sm:text-3xl">Rs {{ number_format($summary?->paid ?? 0, 2) }}</div><p class="relative mt-1 text-xs text-emerald-50">Successfully paid to your account</p></div>
                <div class="group relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-700 p-5 text-white shadow-xl shadow-indigo-200/60 transition hover:-translate-y-1"><div class="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/10"></div><div class="relative flex items-center justify-between"><span class="text-[10px] font-black uppercase tracking-wider text-indigo-100">Lifetime earnings</span><span class="grid h-10 w-10 place-items-center rounded-xl bg-white/15 text-lg">★</span></div><div class="relative mt-5 text-2xl font-black sm:text-3xl">Rs {{ number_format($summary?->lifetime ?? 0, 2) }}</div><p class="relative mt-1 text-xs text-indigo-100">All commission generated to date</p></div>
            </div>

            <form method="GET" action="{{ ($portalPreview ?? false) ? route('customers.commissions', $customer) : route('customer.commissions') }}" class="rounded-3xl border border-indigo-100 bg-white/95 p-5 shadow-xl shadow-slate-200/60 backdrop-blur dark:border-slate-700 dark:bg-slate-900">
                <div class="mb-4 flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-indigo-100 text-indigo-700">⌕</span><div><h2 class="font-black text-slate-950 dark:text-white">Find a transaction</h2><p class="text-xs text-slate-500 dark:text-slate-300">Filter earnings by member, project, level or payout status.</p></div></div>
                <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-[1.5fr_1fr_.7fr_.8fr_auto_auto] xl:items-end">
                    <label class="text-[10px] font-black uppercase tracking-wide text-slate-500">Search team or reference<input name="search" value="{{ request('search') }}" placeholder="Name, referral code, receipt or booking" class="mt-1.5 w-full rounded-xl border-slate-300 py-3 text-sm font-normal normal-case tracking-normal dark:border-slate-600 dark:bg-slate-800 dark:text-white"></label>
                    <label class="text-[10px] font-black uppercase tracking-wide text-slate-500">Project<select name="project" class="mt-1.5 w-full rounded-xl border-slate-300 py-3 text-sm font-normal normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((string) request('project') === (string) $project->id)>{{ $project->name }}</option>@endforeach</select></label>
                    <label class="text-[10px] font-black uppercase tracking-wide text-slate-500">Level<select name="level" class="mt-1.5 w-full rounded-xl border-slate-300 py-3 text-sm font-normal normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"><option value="">All levels</option>@foreach([1,2,3] as $level)<option value="{{ $level }}" @selected((string) request('level') === (string) $level)>Level {{ $level }}</option>@endforeach</select></label>
                    <label class="text-[10px] font-black uppercase tracking-wide text-slate-500">Status<select name="status" class="mt-1.5 w-full rounded-xl border-slate-300 py-3 text-sm font-normal normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"><option value="">All statuses</option>@foreach(['earned' => 'Earned', 'paid' => 'Paid out', 'reversed' => 'Reversed'] as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></label>
                    <button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-black text-white shadow-md hover:bg-indigo-700">Apply filters</button><a href="{{ ($portalPreview ?? false) ? route('customers.commissions', $customer) : route('customer.commissions') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-center text-sm font-bold text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300">Clear</a>
                </div>
            </form>
            @include('customer-commission-table')
        </div>
    </div>
</x-app-layout>
