<x-app-layout>


    <div class="customer-portal relative min-h-screen overflow-hidden bg-gradient-to-br from-indigo-50 via-white to-cyan-50 py-6 dark:from-slate-950 dark:via-slate-950 dark:to-indigo-950/40 sm:py-8">
        <div class="pointer-events-none absolute -left-32 top-32 h-96 w-96 rounded-full bg-violet-200/40 blur-3xl dark:bg-violet-900/20"></div>
        <div class="pointer-events-none absolute -right-32 top-[38rem] h-96 w-96 rounded-full bg-cyan-200/40 blur-3xl dark:bg-cyan-900/20"></div>
        <div class="relative mx-auto max-w-7xl space-y-6 px-4 sm:px-6">
        @if($portalPreview ?? false)<div class="sticky top-3 z-40 flex flex-col gap-3 rounded-xl border border-violet-300 bg-violet-950 px-4 py-3 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between"><div><b class="text-sm">Admin portal preview</b><p class="text-xs text-violet-200">Viewing {{ $customer->name }}'s customer portal in read-only mode.</p></div><div class="flex gap-2"><a href="{{ route('customers.team',$customer) }}" class="rounded-lg bg-violet-800 px-4 py-2 text-center text-xs font-black text-white">View team</a><a href="{{ route('customers.show',$customer) }}" class="rounded-lg bg-white px-4 py-2 text-center text-xs font-black text-violet-800">Exit preview</a></div></div>@endif
        @if(session('success'))<div class="flex items-start gap-3 rounded-xl border border-green-200 bg-green-50 p-4 text-sm font-medium text-green-800 shadow-sm"><span class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-green-600 text-xs text-white">✓</span>{{ session('success') }}</div>@endif
        @if($errors->any())<div class="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-800 shadow-sm"><span class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-red-600 text-xs text-white">!</span>{{ $errors->first() }}</div>@endif

        @if(!$customer)
            <div class="rounded-2xl border border-amber-200 bg-amber-50 p-8 text-center text-amber-900 shadow-sm"><div class="text-lg font-bold">Account not connected</div><p class="mt-1 text-sm">Your login is not linked to a customer record. Please contact the office.</p></div>
        @else
            @php($customerInitials = collect(preg_split('/\s+/', trim($customer->name)))->filter()->take(2)->map(fn($part) => strtoupper(substr($part, 0, 1)))->join(''))
            <section class="relative isolate overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-indigo-900 to-violet-700 text-white shadow-2xl shadow-indigo-300/60 dark:shadow-none">
                <div class="absolute -right-20 -top-24 -z-10 h-80 w-80 rounded-full bg-fuchsia-400/30 blur-3xl"></div>
                <div class="absolute -bottom-32 left-1/3 -z-10 h-72 w-72 rounded-full bg-cyan-300/20 blur-3xl"></div>
                <div class="absolute inset-0 -z-10 opacity-[.07]" style="background-image:radial-gradient(circle at 1px 1px,#fff 1px,transparent 0);background-size:24px 24px"></div>
                <div class="grid lg:grid-cols-[1.2fr_.8fr]">
                    <div class="p-6 sm:p-9">
                        <span class="sr-only">My property account</span>
                        <div class="mb-6 inline-flex items-center gap-3 rounded-2xl bg-white/10 p-2 pr-4 backdrop-blur">
                            <span class="flex h-11 w-18 shrink-0 flex-none items-center justify-center rounded-xl p-1.5">
                                <img src="{{ asset('logo.svg') }}" alt="MMS Group logo" class="h-full w-full object-contain">
                            </span>
                            <span>
                                <span class="block text-sm font-black tracking-wide text-white">MMS Group</span>
                                <span class="block text-[9px] font-bold uppercase tracking-[.18em] text-indigo-200">Customer portal</span>
                            </span>
                        </div>
                        <div class="flex items-center gap-4">
                            <div class="relative grid h-16 w-16 shrink-0 place-items-center rounded-2xl border border-white/30 bg-gradient-to-br from-fuchsia-500 to-indigo-700 text-lg font-black shadow-xl ring-4 ring-white/10">
                                {{ $customerInitials ?: 'CU' }}
                                <span class="absolute -bottom-1 -right-1 h-4 w-4 rounded-full border-[3px] border-indigo-900 bg-emerald-400"></span>
                            </div>
                            <div class="min-w-0">
                                <div class="inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-emerald-200"><span class="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-300"></span>Customer account active</div>
                                <h3 class="mt-2 truncate text-2xl font-black tracking-tight sm:text-4xl">{{ $customer->name }}</h3>
                                <p class="mt-1 text-xs text-indigo-200">{{ $customer->file_no ? 'File '.$customer->file_no.' · ' : '' }}Member since {{ $customer->created_at->format('M Y') }}</p>
                            </div>
                        </div>
                        <p class="mt-6 max-w-xl text-sm leading-6 text-indigo-100">Your complete property journey—from booking and approval to every verified installment—in one secure account.</p>
                        <div class="mt-6 flex flex-wrap gap-2">
                            @unless($portalPreview ?? false)
                                <a href="{{ route('customer.bookings.create') }}" class="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-indigo-800 shadow-xl transition hover:-translate-y-0.5 hover:bg-indigo-50"><span class="text-lg leading-none">＋</span> Book a plot</a>
                                <a href="{{ route('customer.team') }}" class="inline-flex items-center rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-bold text-white backdrop-blur transition hover:bg-white/20">My team</a>
                                <a href="{{ route('profile.edit') }}" class="inline-flex items-center rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-bold text-white backdrop-blur transition hover:bg-white/20">My profile</a>
                            @endunless
                        </div>
                    </div>
                    <div class="border-t border-white/10 bg-white/[.07] p-6 backdrop-blur-md lg:border-l lg:border-t-0 sm:p-8">
                        <div class="flex items-center justify-between"><div><div class="text-[10px] font-black uppercase tracking-[.2em] text-indigo-200">Account snapshot</div><div class="mt-1 text-sm font-bold text-white">Your property portfolio</div></div><span class="grid h-10 w-10 place-items-center rounded-xl border border-white/15 bg-white/10 text-lg">⌂</span></div>
                        <div class="mt-6 grid grid-cols-2 gap-3">
                            <div class="rounded-2xl border border-white/10 bg-white/10 p-4"><div class="text-[9px] font-bold uppercase tracking-wider text-indigo-200">Total bookings</div><div class="mt-1 text-2xl font-black">{{ $bookings->count() }}</div></div>
                            <div class="rounded-2xl border border-white/10 bg-white/10 p-4"><div class="text-[9px] font-bold uppercase tracking-wider text-indigo-200">Due now</div><div class="mt-1 truncate text-lg font-black text-amber-300">Rs {{ number_format($dueNow) }}</div></div>
                        </div>
                        @if($showReferralCode)
                            <div x-data="{ copied:false }" class="mt-3 rounded-2xl border border-white/10 bg-gradient-to-r from-white/10 to-fuchsia-300/10 p-4">
                                <div class="flex items-end justify-between gap-3"><div><div class="text-[9px] font-bold uppercase tracking-[.16em] text-indigo-200">Referral code</div><div class="mt-1 font-mono text-lg font-black tracking-wider">{{ $customer->referral_code }}</div></div><button type="button" @click="navigator.clipboard.writeText(@js(route('register', ['ref' => $customer->referral_code]))); copied=true; setTimeout(()=>copied=false,1500)" class="rounded-lg bg-white px-3 py-2 text-[10px] font-black text-indigo-700" x-text="copied ? 'Link copied ✓' : 'Copy referral link'">Copy referral link</button></div>
                            </div>
                        @endif
                    </div>
                </div>
            </section>

            <section class="overflow-hidden rounded-2xl border border-indigo-100 bg-white shadow-lg shadow-indigo-100/50">
                <div class="flex items-center justify-between border-b border-slate-100 p-4 sm:p-5"><div><div class="flex items-center gap-2"><h3 class="font-black text-slate-950">Account notifications</h3>@if($unreadNotificationCount)<span class="rounded-full bg-rose-500 px-2 py-0.5 text-[10px] font-black text-white">{{ $unreadNotificationCount }} new</span>@endif</div><p class="mt-1 text-xs text-slate-500">Latest booking, payment and verification activity</p></div>@unless($portalPreview ?? false)<a href="{{ route('customer.notifications.index') }}" class="text-xs font-black text-indigo-600">View all →</a>@endunless</div>
                <div class="grid divide-y divide-slate-100 lg:grid-cols-5 lg:divide-x lg:divide-y-0">
                    @forelse($notifications as $notification)
                        @php($category = $notification->data['category'] ?? 'account')
                        <div class="relative p-4 {{ $notification->read_at ? 'bg-white' : 'bg-indigo-50/60' }}"><div class="flex items-start gap-3"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-lg text-xs font-black {{ $category === 'payment' ? 'bg-emerald-100 text-emerald-700' : ($category === 'reminder' ? 'bg-amber-100 text-amber-700' : 'bg-violet-100 text-violet-700') }}">{{ $category === 'payment' ? 'Rs' : ($category === 'reminder' ? '!' : '#') }}</span><div class="min-w-0"><b class="block text-xs text-slate-900">{{ $notification->data['title'] ?? 'Account update' }}</b><p class="mt-1 line-clamp-2 text-[11px] leading-4 text-slate-500">{{ $notification->data['message'] ?? '' }}</p><span class="mt-2 block text-[9px] text-slate-400">{{ $notification->created_at->diffForHumans() }}</span></div></div>@unless($notification->read_at)<span class="absolute right-3 top-3 h-2 w-2 rounded-full bg-indigo-600"></span>@endunless</div>
                    @empty<div class="p-6 text-center text-sm text-slate-400 lg:col-span-5">No account notifications yet.</div>@endforelse
                </div>
            </section>

            <div class="grid gap-4 sm:grid-cols-3">
                <div class="group relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-800 p-5 text-white shadow-xl shadow-indigo-200/70 transition hover:-translate-y-1 hover:shadow-2xl"><div class="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/10"></div><div class="relative flex items-center justify-between"><span class="text-xs font-black uppercase tracking-wider text-indigo-100">Active bookings</span><span class="grid h-11 w-11 place-items-center rounded-2xl bg-white/15 text-lg font-black ring-1 ring-white/20">#</span></div><div class="relative mt-5 text-4xl font-black">{{ $bookings->whereIn('status', ['active','approved'])->count() }}</div><div class="relative mt-1 text-xs text-indigo-200">Property plans on your account</div></div>
                <div class="group relative overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-500 to-teal-700 p-5 text-white shadow-xl shadow-emerald-200/70 transition hover:-translate-y-1 hover:shadow-2xl"><div class="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/10"></div><div class="relative flex items-center justify-between"><span class="text-xs font-black uppercase tracking-wider text-emerald-50">Verified payments</span><span class="grid h-11 w-11 place-items-center rounded-2xl bg-white/15 text-lg font-black ring-1 ring-white/20">✓</span></div><div class="relative mt-5 text-2xl font-black sm:text-3xl">Rs {{ number_format($paid, 2) }}</div><div class="relative mt-1 text-xs text-emerald-100">Successfully credited to your account</div></div>
                <div class="group relative overflow-hidden rounded-3xl bg-gradient-to-br from-amber-400 to-orange-600 p-5 text-white shadow-xl shadow-amber-200/70 transition hover:-translate-y-1 hover:shadow-2xl"><div class="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/10"></div><div class="relative flex items-center justify-between"><span class="text-xs font-black uppercase tracking-wider text-amber-50">Due now</span><span class="grid h-11 w-11 place-items-center rounded-2xl bg-white/15 text-lg font-black ring-1 ring-white/20">↗</span></div><div class="relative mt-5 text-2xl font-black sm:text-3xl">Rs {{ number_format($dueNow, 2) }}</div><div class="relative mt-1 text-xs text-amber-100">First payment or installments currently due</div></div>
            </div>

            <div id="payments" class="scroll-mt-20"></div>
            @forelse($bookings as $booking)
                @php($pendingInstallmentIds = $booking->payments->where('status', 'pending')->pluck('installment_schedule_id')->filter())
                @php($firstPayment = $booking->payments->whereNull('installment_schedule_id')->sortByDesc('payment_date')->first())
                @php($firstPaymentVerified = $firstPayment?->status === 'verified')
                @php($payableInstallments = $booking->status === 'active' && $firstPaymentVerified ? $booking->installments->whereIn('status', ['pending', 'partial'])->filter(fn ($item) => (float) $item->paid_amount < (float) $item->total_due && !$pendingInstallmentIds->contains($item->id)) : collect())
                @php($bookingPaid = (float) $booking->payments->where('status', 'verified')->sum('amount'))
                @php($paymentProgress = (float) $booking->total_price > 0 ? min(100, $bookingPaid / (float) $booking->total_price * 100) : 0)
                <section class="overflow-hidden rounded-3xl border border-indigo-100 bg-white shadow-xl shadow-slate-200/70">
                    <div class="border-b border-gray-100 p-5 sm:p-6">
                        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div class="mb-2 flex flex-wrap items-center gap-2"><span class="rounded-md bg-indigo-600 px-2.5 py-1 font-mono text-xs font-bold text-white">{{ $booking->booking_number }}</span><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $booking->status==='active'?'bg-green-50 text-green-700':'bg-gray-100 text-gray-700' }}">{{ ucfirst($booking->status) }}</span><span class="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-bold text-violet-700">{{ $booking->payment_plan === 'cash' ? 'Cash plan' : 'Installment plan' }}</span></div><h3 class="text-xl font-bold text-gray-900">{{ $booking->project->name }}</h3><p class="mt-1 text-sm text-gray-500">{{ $booking->package->name }} · {{ $booking->package->size_marla }} marla{{ $booking->payment_plan === 'installment' ? ' · '.$booking->package->months.' months' : '' }}</p></div><div class="rounded-xl bg-gray-50 px-4 py-3 text-left sm:text-right"><div class="text-xs font-medium uppercase tracking-wide text-gray-400">{{ $booking->payment_plan === 'cash' ? 'Cash price' : 'Installment price' }}</div><div class="mt-1 text-xl font-bold text-gray-900">Rs {{ number_format($booking->total_price, 2) }}</div></div></div>
                        <div class="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-5"><div class="rounded-xl border border-gray-100 bg-gray-50/60 p-3"><span class="text-xs text-gray-500">Booking number</span><b class="mt-1 block font-mono text-sm text-gray-900">{{ $booking->booking_number }}</b></div><div class="rounded-xl border border-gray-100 bg-gray-50/60 p-3"><span class="text-xs text-gray-500">First payment</span><b class="mt-1 block text-sm text-gray-900">Rs {{ number_format($booking->booking_amount, 2) }}</b></div><div class="rounded-xl border border-gray-100 bg-gray-50/60 p-3"><span class="text-xs text-gray-500">Monthly installment</span><b class="mt-1 block text-sm text-gray-900">Rs {{ number_format($booking->package->monthly_amount, 2) }}</b></div><div class="rounded-xl border border-gray-100 bg-gray-50/60 p-3"><span class="text-xs text-gray-500">Booking date</span><b class="mt-1 block text-sm text-gray-900">{{ $booking->booking_date->format('d M Y') }}</b></div><div class="rounded-xl border border-amber-200 bg-amber-50 p-3"><span class="text-xs font-semibold text-amber-700">Due now</span><b class="mt-1 block text-sm text-amber-900">Rs {{ number_format($booking->due_now, 2) }}</b></div></div>
                        @if($booking->allotment)<div class="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div><div class="text-xs font-black uppercase tracking-wider text-emerald-600">Plot allotted</div><div class="mt-1 text-lg font-black text-emerald-950">{{ $booking->allotment->plot->block->name }} · Plot {{ $booking->allotment->plot->plot_number }}</div><div class="text-xs text-emerald-700">{{ number_format($booking->allotment->plot->size_marla,2) }} marla · {{ $booking->allotment->allotment_number }}</div></div><div class="text-sm font-bold text-emerald-800">{{ $booking->allotment->allotment_date->format('d M Y') }}</div></div>@endif
                        <div class="mt-5 rounded-xl bg-indigo-50/70 p-4"><div class="mb-2 flex items-center justify-between text-xs font-bold"><span class="text-indigo-800">Payment progress</span><span class="text-indigo-600">{{ number_format($paymentProgress, 1) }}%</span></div><div class="h-2.5 overflow-hidden rounded-full bg-indigo-100"><div class="h-full rounded-full bg-gradient-to-r from-indigo-600 to-violet-500 shadow-sm" style="width: {{ $paymentProgress }}%"></div></div><div class="mt-2 flex justify-between text-xs text-gray-500"><span>Paid Rs {{ number_format($bookingPaid, 2) }}</span><span>Total Rs {{ number_format($booking->total_price, 2) }}</span></div></div>
                    </div>

                    @if($booking->status === 'pending')
                        <div class="border-b border-amber-100 bg-amber-50 p-5 text-sm text-amber-900 sm:p-6"><div class="flex items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-amber-200 font-black text-amber-800">⌛</span><div><div class="font-black">Awaiting office approval</div><div class="mt-1 text-xs text-amber-700">Your first payment of Rs {{ number_format($booking->booking_amount, 2) }} will become available after approval.</div></div></div></div>
                    @elseif($booking->status === 'approved' && !$firstPaymentVerified)
                        @if($firstPayment?->status === 'pending')
                            <div class="border-b border-amber-100 bg-amber-50 p-5 text-sm text-amber-900 sm:p-6"><div class="flex items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-amber-200 font-black text-amber-800">✓</span><div><div class="font-black">First payment under review</div><div class="mt-1 text-xs text-amber-700">Your proof for Rs {{ number_format($firstPayment->amount, 2) }} has been submitted. Installment payments unlock after verification.</div></div></div></div>
                        @elseif(!($portalPreview ?? false))
                            <div class="border-b border-emerald-100 bg-emerald-50 p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="text-xs font-black uppercase tracking-wider text-emerald-600">Booking approved</div><h4 class="mt-1 text-lg font-black text-emerald-950">Pay your first payment</h4><p class="mt-1 text-sm text-emerald-700">Upload payment proof to confirm your approved booking.</p></div><div class="rounded-xl bg-white px-5 py-3 shadow-sm"><div class="text-xs text-gray-500">Amount due</div><div class="text-xl font-black text-gray-950">Rs {{ number_format($booking->booking_amount, 2) }}</div></div></div>
                                <form method="POST" action="{{ route('customer.payments.store') }}" enctype="multipart/form-data" data-compress-proof class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@csrf<input type="hidden" name="booking_id" value="{{ $booking->id }}"><input type="hidden" name="payment_type" value="booking">@include('customer-payments._method-select')<label class="text-sm font-semibold text-gray-700">Transaction reference<input name="transaction_reference" maxlength="100" class="mt-1.5 w-full rounded-lg border-gray-300 bg-white"></label><label class="text-sm font-semibold text-gray-700">Payment proof<input type="file" name="proof" accept="image/jpeg,image/png,image/webp,image/gif,image/bmp,image/heic,image/heif,application/pdf,.jfif" required class="mt-2 block w-full text-xs"><span class="mt-1 block text-[10px] font-bold text-amber-600">JPG, PNG, WebP, GIF, BMP, HEIC or PDF · Images compress below 300 KB</span></label><div class="flex items-end"><button class="w-full rounded-lg bg-emerald-600 px-5 py-3 font-black text-white hover:bg-emerald-700 disabled:cursor-wait disabled:opacity-70">Submit first payment</button></div></form>
                            </div>
                        @endif
                    @endif

                    @if($payableInstallments->isNotEmpty() && !($portalPreview ?? false))
                    <form id="payment-form-{{ $booking->id }}" method="POST" action="{{ route('customer.payments.store') }}" enctype="multipart/form-data" data-compress-proof class="hidden scroll-mt-20 overflow-hidden border-b border-indigo-100 bg-white">@csrf
                        <input type="hidden" name="booking_id" value="{{ $booking->id }}"><input type="hidden" name="payment_type" value="installment">
                        <div class="relative overflow-hidden bg-gradient-to-r from-indigo-700 via-violet-700 to-purple-800 p-5 text-white sm:p-6">
                            <div class="absolute -right-8 -top-10 h-32 w-32 rounded-full bg-fuchsia-400/20 blur-2xl"></div>
                            <div class="relative flex items-start justify-between gap-4">
                                <div class="flex items-start gap-3">
                                    <span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/20 bg-white/10 shadow-lg backdrop-blur"><svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 14.25 11.25 16.5 15 12.75m6-1.5a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/></svg></span>
                                    <div><div class="text-[10px] font-black uppercase tracking-[.2em] text-indigo-200">Secure payment submission</div><h4 class="mt-1 text-xl font-black">Pay an installment</h4><p class="mt-1 text-xs text-indigo-100">Choose the installment, transfer the amount, then upload your proof.</p></div>
                                </div>
                                <button type="button" onclick="this.closest('form').classList.add('hidden')" class="rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-xs font-bold text-white/80 transition hover:bg-white/20 hover:text-white">✕ Close</button>
                            </div>
                            <div class="relative mt-5 grid grid-cols-3 gap-2 text-center text-[9px] font-bold uppercase tracking-wide text-indigo-100">
                                <div class="rounded-lg bg-white/15 px-2 py-2"><b class="mr-1 text-white">1</b> Select</div><div class="rounded-lg bg-white/10 px-2 py-2"><b class="mr-1 text-white">2</b> Transfer</div><div class="rounded-lg bg-white/10 px-2 py-2"><b class="mr-1 text-white">3</b> Upload</div>
                            </div>
                        </div>

                        <div class="grid gap-5 bg-gradient-to-b from-indigo-50/70 to-white p-5 lg:grid-cols-2 sm:p-6">
                            <div class="space-y-4 rounded-2xl border border-indigo-100 bg-white p-4 shadow-sm">
                                <div><h5 class="font-black text-gray-900">Payment amount</h5><p class="text-xs text-gray-500">The remaining installment balance is filled automatically.</p></div>
                                <label class="block text-xs font-bold uppercase tracking-wide text-gray-500">Installment<select id="payment-installment-{{ $booking->id }}" name="installment_id" required onchange="document.getElementById('payment-amount-{{ $booking->id }}').value=this.options[this.selectedIndex].dataset.balance" class="mt-1.5 w-full rounded-xl border-gray-300 bg-white py-3 text-sm font-bold text-gray-900 focus:border-indigo-500 focus:ring-indigo-500">@foreach($payableInstallments as $item)<option value="{{ $item->id }}" data-balance="{{ number_format((float)$item->total_due-(float)$item->paid_amount, 2, '.', '') }}">Month {{ $item->installment_number }} — due {{ $item->due_date->format('d M Y') }}</option>@endforeach</select></label>
                                <label class="block text-xs font-bold uppercase tracking-wide text-gray-500">Amount to submit (Rs)<div class="relative mt-1.5"><span class="absolute left-3 top-1/2 -translate-y-1/2 text-sm font-black text-indigo-600">Rs</span><input id="payment-amount-{{ $booking->id }}" type="number" name="amount" min="0.01" step="0.01" value="{{ number_format((float)$payableInstallments->first()->total_due-(float)$payableInstallments->first()->paid_amount, 2, '.', '') }}" readonly required class="w-full cursor-not-allowed rounded-xl border-indigo-200 bg-indigo-50 py-3 pl-10 text-lg font-black text-indigo-950 focus:border-indigo-200 focus:ring-0"></div><span class="mt-1.5 flex items-center gap-1 text-[10px] font-semibold normal-case text-indigo-500">🔒 The exact remaining balance is required.</span></label>
                                <label class="block text-xs font-bold uppercase tracking-wide text-gray-500">Transaction reference <span class="font-normal normal-case text-gray-400">(optional)</span><input name="transaction_reference" maxlength="100" placeholder="Bank reference or transaction ID" class="mt-1.5 w-full rounded-xl border-gray-300 bg-white py-3 text-sm focus:border-indigo-500 focus:ring-indigo-500"></label>
                            </div>

                            <div class="rounded-2xl border border-indigo-100 bg-white p-4 shadow-sm">
                                <div class="mb-4"><h5 class="font-black text-gray-900">Where to pay</h5><p class="text-xs text-gray-500">Select a method to see its account details.</p></div>
                                @include('customer-payments._method-select')
                            </div>

                            <label class="block rounded-2xl border border-indigo-100 bg-white p-4 shadow-sm lg:col-span-2">
                                <span class="text-sm font-black text-gray-900">Upload payment proof</span><span class="mt-0.5 block text-xs font-normal text-gray-500">Use a clear screenshot or deposit slip so the office can verify it quickly.</span>
                                <div class="mt-3 flex min-h-24 items-center justify-center rounded-xl border-2 border-dashed border-indigo-200 bg-indigo-50/50 p-5 transition hover:border-indigo-400 hover:bg-indigo-50"><input type="file" name="proof" accept="image/jpeg,image/png,image/webp,image/gif,image/bmp,image/heic,image/heif,application/pdf,.jfif" required class="block w-full text-xs text-gray-600 file:mr-4 file:rounded-lg file:border-0 file:bg-indigo-600 file:px-4 file:py-2.5 file:text-xs file:font-bold file:text-white hover:file:bg-indigo-700"></div>
                                <span class="mt-2 block text-[10px] font-bold text-amber-600">JPG, PNG, WebP, GIF, BMP, HEIC or PDF · Images compress below 300 KB</span>
                            </label>

                            <div class="flex flex-col gap-3 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 sm:flex-row sm:items-center sm:justify-between lg:col-span-2">
                                <div class="flex items-center gap-2 text-xs text-emerald-800"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-emerald-200 font-black">✓</span><span>Your payment will remain under review until verified by the office.</span></div>
                                <button class="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 px-6 py-3 text-sm font-black text-white shadow-lg shadow-emerald-200 transition hover:-translate-y-0.5 hover:from-emerald-700 hover:to-teal-700 sm:w-auto"><svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5"/></svg>Submit for verification</button>
                            </div>
                        </div>
                    </form>
                    @endif

                    <div x-data="{ accountTab: '{{ $booking->payment_plan === 'cash' ? 'payments' : 'installments' }}' }" class="border-t border-gray-100">
                        <div class="border-b border-gray-100 bg-gray-50/70 p-3 sm:px-6">
                            <div class="grid grid-cols-2 gap-2 rounded-xl border border-gray-200 bg-white p-1.5 shadow-sm">
                                <button type="button" @click="accountTab = 'installments'" :class="accountTab === 'installments' ? 'bg-indigo-600 text-white shadow-sm' : 'bg-indigo-50 text-indigo-700 hover:bg-indigo-100'" class="flex min-h-11 items-center justify-center gap-2 rounded-lg px-3 py-2 text-xs font-black transition sm:text-sm">
                                    <span>Installment schedule</span><span :class="accountTab === 'installments' ? 'bg-white text-indigo-700' : 'bg-indigo-600 text-white'" class="rounded-full px-2 py-0.5 text-[10px] shadow-sm">{{ $booking->installments->count() }}</span>
                                </button>
                                <button type="button" @click="accountTab = 'payments'" :class="accountTab === 'payments' ? 'bg-emerald-600 text-white shadow-sm' : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'" class="flex min-h-11 items-center justify-center gap-2 rounded-lg px-3 py-2 text-xs font-black transition sm:text-sm">
                                    <span>Payment history</span><span :class="accountTab === 'payments' ? 'bg-white text-emerald-700' : 'bg-emerald-600 text-white'" class="rounded-full px-2 py-0.5 text-[10px] shadow-sm">{{ $booking->payments->count() }}</span>
                                </button>
                            </div>
                        </div>
                        <div x-show="accountTab === 'installments'" x-cloak class="p-5 sm:p-6"><div class="mb-4"><h4 class="font-bold text-gray-900">Installment schedule</h4><p class="mt-1 text-xs text-gray-500">Installments appear when their payment month begins.</p></div><div class="overflow-x-auto"><table class="installment-table w-full min-w-[680px] text-sm"><thead><tr class="border-b border-gray-100 text-left text-xs uppercase tracking-wide text-gray-400"><th class="pb-3">Month</th><th class="pb-3">Due date</th><th class="pb-3">Amount</th><th class="pb-3">Paid</th><th class="pb-3">Status</th><th class="pb-3"></th></tr></thead><tbody>@forelse($booking->installments as $installment)<tr class="border-b border-gray-50"><td class="py-3 font-bold text-gray-900">{{ $installment->installment_number }}</td><td class="py-3 text-gray-600">{{ $installment->due_date->format('d M Y') }}</td><td class="py-3 font-medium">Rs {{ number_format($installment->total_due, 2) }}</td><td class="py-3 text-gray-600">Rs {{ number_format($installment->paid_amount, 2) }}</td><td class="py-3">@if($pendingInstallmentIds->contains($installment->id))<span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-700">Under review</span>@else<span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $installment->status==='paid'?'bg-green-100 text-green-700':($installment->status==='partial'?'bg-blue-100 text-blue-700':'bg-gray-100 text-gray-600') }}">{{ ucfirst($installment->status) }}</span>@endif</td><td class="py-3 text-right">@if(in_array($installment->status, ['pending','partial']) && (float)$installment->paid_amount < (float)$installment->total_due && !$pendingInstallmentIds->contains($installment->id))<a href="#payment-form-{{ $booking->id }}" onclick="const form=document.getElementById('payment-form-{{ $booking->id }}');form.classList.remove('hidden');const select=document.getElementById('payment-installment-{{ $booking->id }}');select.value='{{ $installment->id }}';select.dispatchEvent(new Event('change'))" class="whitespace-nowrap rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white shadow-sm hover:bg-indigo-700">Pay installment</a>@endif</td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-gray-400">No installment is due this month yet.</td></tr>@endforelse</tbody></table></div></div>
                        <div x-show="accountTab === 'payments'" x-cloak class="p-5 sm:p-6"><div class="mb-4"><h4 class="font-bold text-gray-900">Payment history</h4><p class="mt-1 text-xs text-gray-500">Receipts and verification status</p></div><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-sm"><thead><tr class="border-b border-gray-100 text-left text-xs uppercase tracking-wide text-gray-400"><th class="pb-3">Receipt</th><th class="pb-3">Date</th><th class="pb-3">Amount</th><th class="pb-3">Status</th><th class="pb-3">Review notes</th><th class="pb-3"></th></tr></thead><tbody>@forelse($booking->payments as $payment)<tr class="border-b border-gray-50 align-top"><td class="py-3 font-mono text-xs font-bold text-gray-700">{{ $payment->receipt_number }}</td><td class="py-3 text-gray-600">{{ $payment->payment_date->format('d M Y') }}</td><td class="py-3 font-bold text-gray-900">Rs {{ number_format($payment->amount, 2) }}</td><td class="py-3"><span class="whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-bold {{ $payment->status==='verified'?'bg-green-100 text-green-700':($payment->status==='pending'?'bg-amber-100 text-amber-700':'bg-red-100 text-red-700') }}">{{ $payment->status==='pending'?'Under review':ucfirst($payment->status) }}</span></td><td class="py-3 pr-4">@if($payment->status !== 'pending' && filled($payment->verification_notes))<div class="max-w-xs whitespace-pre-line rounded-lg border {{ $payment->status === 'verified' ? 'border-emerald-100 bg-emerald-50 text-emerald-800' : 'border-rose-100 bg-rose-50 text-rose-800' }} px-2.5 py-2 text-[10px] leading-4">{{ $payment->verification_notes }}</div>@else<span class="text-gray-400">—</span>@endif</td><td class="py-3 text-right">@if($portalPreview ?? false)<span class="text-xs text-gray-400">Read only</span>@else<a href="{{ route('customer.payments.receipt', $payment) }}" class="whitespace-nowrap font-bold text-indigo-600 hover:text-indigo-800">View receipt</a>@endif</td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-gray-400">No payments recorded yet.</td></tr>@endforelse</tbody></table></div></div>
                    </div>
                </section>
            @empty
                <div class="rounded-2xl border border-gray-100 bg-white p-12 text-center shadow-sm"><div class="text-lg font-bold text-gray-700">No bookings yet</div><p class="mt-1 text-sm text-gray-400">No property bookings are linked to your account.</p></div>
            @endforelse
        @endif
    </div></div>
</x-app-layout>
