<section class="overflow-hidden rounded-3xl border border-indigo-100 bg-white shadow-xl shadow-slate-200/70 dark:border-slate-700 dark:bg-slate-900 dark:shadow-none">
    <div class="flex flex-col gap-2 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800"><div><h3 class="text-lg font-black text-slate-950 dark:text-white">All transactions</h3><p class="text-xs text-slate-500 dark:text-slate-300">Commission generated from verified payments across your three-level team.</p></div><span class="w-fit rounded-full bg-indigo-50 px-3 py-1 text-[10px] font-black text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">{{ $commissions->total() }} records</span></div>
    <div class="divide-y divide-slate-100 dark:divide-slate-800 md:hidden">
        @forelse($commissions as $commission)
            @php($levelTheme = match((int)$commission->level) {1 => 'bg-violet-100 text-violet-700', 2 => 'bg-cyan-100 text-cyan-700', default => 'bg-amber-100 text-amber-700'})
            <article class="p-4">
                <div class="flex items-start justify-between gap-3">
                    <div class="min-w-0"><h4 class="truncate font-black text-slate-950 dark:text-white">{{ $commission->booking->customer->name }}</h4>@if($showReferralCode)<p class="mt-0.5 truncate font-mono text-[10px] text-slate-400">{{ $commission->booking->customer->referral_code }}</p>@endif</div>
                    <span class="inline-flex shrink-0 items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-black {{ $commission->status === 'earned' ? 'bg-amber-100 text-amber-700' : ($commission->status === 'paid' ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700') }}"><span class="h-1.5 w-1.5 rounded-full {{ $commission->status === 'earned' ? 'bg-amber-500' : ($commission->status === 'paid' ? 'bg-emerald-500' : 'bg-rose-500') }}"></span>{{ $commission->status === 'paid' ? 'Paid out' : ucfirst($commission->status) }}</span>
                </div>
                <div class="mt-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-800">
                    <div class="flex items-start justify-between gap-3"><div><div class="text-[9px] font-black uppercase tracking-wider text-slate-400">Your commission</div><div class="mt-1 text-lg font-black {{ $commission->status === 'reversed' ? 'text-rose-600 line-through' : 'text-emerald-600 dark:text-emerald-400' }}">Rs {{ number_format($commission->amount, 2) }}</div></div><span class="rounded-lg px-2.5 py-1.5 text-[10px] font-black {{ $levelTheme }}">L{{ $commission->level }} · {{ $commission->calculation_type === 'fixed' ? 'Rs '.number_format($commission->fixed_amount, 2) : number_format($commission->percentage, 2).'%' }}</span></div>
                </div>
                <dl class="mt-3 grid grid-cols-2 gap-2 text-xs">
                    <div class="rounded-xl border border-slate-100 p-3 dark:border-slate-700"><dt class="text-[9px] font-black uppercase text-slate-400">Project</dt><dd class="mt-1 font-bold text-slate-800 dark:text-white">{{ $commission->booking->project->name }}</dd><dd class="mt-0.5 text-[10px] text-slate-400">{{ $commission->booking->package->name }}</dd></div>
                    <div class="rounded-xl border border-slate-100 p-3 dark:border-slate-700"><dt class="text-[9px] font-black uppercase text-slate-400">Customer payment</dt><dd class="mt-1 font-bold text-slate-800 dark:text-white">Rs {{ number_format($commission->payment?->amount ?? 0, 2) }}</dd><dd class="mt-0.5 font-mono text-[10px] text-indigo-600 dark:text-indigo-300">{{ $commission->payment?->receipt_number ?? '—' }}</dd></div>
                </dl>
                <div class="mt-3 flex items-center justify-between gap-3 text-[10px] text-slate-400"><span class="truncate font-mono">{{ $commission->booking->booking_number }}</span><time class="shrink-0 font-bold text-slate-600 dark:text-slate-300">{{ $commission->created_at->format('d M Y') }}</time></div>
            </article>
        @empty
            <div class="p-10 text-center"><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-indigo-100 to-emerald-100 text-xl text-indigo-600 dark:from-slate-800 dark:to-slate-700">%</span><h3 class="mt-3 font-black text-slate-900 dark:text-white">No commission transactions yet.</h3><p class="mt-1 text-sm text-slate-400">Verified team payments and their earnings will appear here.</p></div>
        @endforelse
    </div>
    <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[1050px] text-left text-sm"><thead class="bg-slate-50/90 text-[10px] font-black uppercase tracking-[.1em] text-slate-400 dark:bg-slate-800"><tr><th class="p-4">Date / Receipt</th><th>Team customer</th><th>Booking</th><th>Project / Package</th><th>Customer payment</th><th>Level</th><th>Rate</th><th>Your commission</th><th>Status</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">
        @forelse($commissions as $commission)
            @php($levelTheme = match((int)$commission->level) {1 => 'bg-violet-100 text-violet-700', 2 => 'bg-cyan-100 text-cyan-700', default => 'bg-amber-100 text-amber-700'})
            <tr class="transition hover:bg-indigo-50/50 dark:hover:bg-slate-800/60"><td class="p-4"><b class="block text-xs text-slate-700 dark:text-slate-200">{{ $commission->created_at->format('d M Y') }}</b><span class="mt-1 block font-mono text-[10px] font-bold text-indigo-600 dark:text-indigo-300">{{ $commission->payment?->receipt_number ?? '—' }}</span></td><td><b class="block text-slate-900 dark:text-white">{{ $commission->booking->customer->name }}</b>@if($showReferralCode)<span class="text-[10px] text-slate-400">{{ $commission->booking->customer->referral_code }}</span>@endif</td><td class="font-mono text-xs font-bold text-slate-600 dark:text-slate-300">{{ $commission->booking->booking_number }}</td><td><b class="block text-xs text-slate-800 dark:text-white">{{ $commission->booking->project->name }}</b><span class="text-[10px] text-slate-400">{{ $commission->booking->package->name }}</span></td><td class="font-bold text-slate-700 dark:text-slate-200">Rs {{ number_format($commission->payment?->amount ?? 0, 2) }}</td><td><span class="rounded-lg px-2.5 py-1.5 text-[10px] font-black {{ $levelTheme }}">L{{ $commission->level }}</span></td><td class="font-bold text-slate-600 dark:text-slate-300">{{ $commission->calculation_type === 'fixed' ? 'Rs '.number_format($commission->fixed_amount, 2) : number_format($commission->percentage, 2).'%' }}</td><td class="font-black {{ $commission->status === 'reversed' ? 'text-rose-600 line-through' : 'text-emerald-600 dark:text-emerald-400' }}">Rs {{ number_format($commission->amount, 2) }}</td><td><span class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-black {{ $commission->status === 'earned' ? 'bg-amber-100 text-amber-700' : ($commission->status === 'paid' ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700') }}"><span class="h-1.5 w-1.5 rounded-full {{ $commission->status === 'earned' ? 'bg-amber-500' : ($commission->status === 'paid' ? 'bg-emerald-500' : 'bg-rose-500') }}"></span>{{ $commission->status === 'paid' ? 'Paid out' : ucfirst($commission->status) }}</span></td></tr>
        @empty
            <tr><td colspan="9" class="p-14 text-center"><span class="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-gradient-to-br from-indigo-100 to-emerald-100 text-2xl text-indigo-600 dark:from-slate-800 dark:to-slate-700">%</span><h3 class="mt-4 font-black text-slate-900 dark:text-white">No commission transactions yet.</h3><p class="mt-1 text-sm text-slate-400">Verified team payments and their earnings will appear here.</p></td></tr>
        @endforelse
    </tbody></table></div>
    @if($commissions->hasPages())<div class="border-t border-slate-100 p-4 dark:border-slate-800">{{ $commissions->links() }}</div>@endif
</section>
