<x-app-layout>
    <div class="min-h-screen bg-gradient-to-b from-indigo-50/60 via-slate-50 to-white py-6 dark:from-slate-950 dark:via-slate-900 dark:to-gray-950 sm:py-8">
        <div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6">
            <section class="relative isolate overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-800 p-6 text-white shadow-2xl shadow-indigo-200 dark:shadow-none sm:p-8">
                <div class="absolute -right-16 -top-20 -z-10 h-64 w-64 rounded-full bg-fuchsia-500/25 blur-3xl"></div><div class="absolute -bottom-24 left-1/3 -z-10 h-56 w-56 rounded-full bg-cyan-400/20 blur-3xl"></div>
                <div class="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between">
                    <div class="min-w-0">
                        <div class="flex flex-wrap items-center gap-2">
                            <div class="inline-flex items-center rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-indigo-200 backdrop-blur">Management command center</div>
                            <div class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold text-indigo-100 backdrop-blur"><span class="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_12px_#34d399]"></span>Live business overview</div>
                        </div>
                        <h3 class="mt-5 max-w-2xl text-3xl font-black tracking-tight sm:text-4xl">Welcome back, {{ auth()->user()->name }}.</h3>
                        <div class="mt-3 text-lg font-black text-white">Business dashboard</div>
                        <p class="mt-1 max-w-2xl text-sm leading-6 text-indigo-200">Sales, collections, inventory and commissions at a glance.</p>
                    </div>
                    <div class="flex w-full shrink-0 flex-col gap-3 sm:flex-row sm:items-stretch lg:w-auto lg:flex-col">
                        <a href="{{ route('sales.create', ['project' => $projectId]) }}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-indigo-900 shadow-xl transition hover:-translate-y-0.5 hover:bg-indigo-50"><span class="text-lg">+</span> New booking</a>
                        <form method="GET" class="rounded-2xl border border-white/15 bg-white/10 p-4 backdrop-blur-xl">
                            <label class="block text-[10px] font-black uppercase tracking-[.18em] text-indigo-200">Dashboard scope
                                <select name="project" onchange="this.form.submit()" class="mt-2 w-full min-w-64 rounded-xl border-white/20 bg-slate-950/60 text-sm font-bold text-white focus:border-violet-300 focus:ring-violet-300">
                                    <option value="">All projects</option>
                                    @foreach($projects as $project)<option value="{{ $project->id }}" @selected($projectId == $project->id)>{{ $project->name }}</option>@endforeach
                                </select>
                            </label>
                            <div class="mt-2 text-[10px] text-indigo-300">Updated {{ now()->format('d M Y, h:i A') }}</div>
                        </form>
                    </div>
                </div>
            </section>

            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                @php($metrics = [
                    ['label' => 'Verified receipts', 'value' => 'Rs '.number_format($received), 'note' => 'Successfully collected', 'icon' => '✓', 'style' => 'from-indigo-600 to-violet-600 text-white shadow-indigo-200', 'link' => route('payments.index', ['status' => 'verified', 'project' => $projectId])],
                    ['label' => 'Active bookings', 'value' => number_format($activeBookings), 'note' => 'Approved and active plans', 'icon' => '#', 'style' => 'from-white to-indigo-50 text-slate-950 shadow-indigo-100 dark:from-slate-800 dark:to-indigo-950 dark:text-white', 'link' => route('bookings.index', ['project' => $projectId])],
                    ['label' => 'Outstanding', 'value' => 'Rs '.number_format($outstanding), 'note' => 'Remaining installment value', 'icon' => '↗', 'style' => 'from-white to-amber-50 text-slate-950 shadow-amber-100 dark:from-slate-800 dark:to-amber-950 dark:text-white', 'link' => route('installments.index', ['project' => $projectId])],
                    ['label' => 'Overdue', 'value' => 'Rs '.number_format($overdue), 'note' => 'Requires collection follow-up', 'icon' => '!', 'style' => 'from-white to-rose-50 text-slate-950 shadow-rose-100 dark:from-slate-800 dark:to-rose-950 dark:text-white', 'link' => route('installments.index', ['status' => 'overdue', 'project' => $projectId])],
                    ['label' => 'Payable commission', 'value' => 'Rs '.number_format($payableCommission), 'note' => 'Earned and awaiting payout', 'icon' => '%', 'style' => 'from-white to-emerald-50 text-slate-950 shadow-emerald-100 dark:from-slate-800 dark:to-emerald-950 dark:text-white', 'link' => route('customers.index', ['type' => 'agent'])],
                    ['label' => 'Available land', 'value' => number_format($availableMarla / 20, 2).' kanal', 'note' => 'Ready across selected projects', 'icon' => '◇', 'style' => 'from-white to-cyan-50 text-slate-950 shadow-cyan-100 dark:from-slate-800 dark:to-cyan-950 dark:text-white', 'link' => route('projects.index')],
                ])
                @foreach($metrics as $metric)
                    <a href="{{ $metric['link'] }}" class="group relative overflow-hidden rounded-2xl bg-gradient-to-br p-5 shadow-lg transition duration-200 hover:-translate-y-1 hover:shadow-xl {{ $metric['style'] }}"><div class="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-current opacity-[.06]"></div><div class="relative flex items-start justify-between"><div><div class="text-xs font-black uppercase tracking-[.15em] opacity-60">{{ $metric['label'] }}</div><div class="mt-3 text-2xl font-black tracking-tight sm:text-3xl">{{ $metric['value'] }}</div><div class="mt-2 text-xs font-medium opacity-60">{{ $metric['note'] }}</div></div><span class="grid h-11 w-11 place-items-center rounded-2xl bg-current text-lg font-black shadow-sm"><i class="not-italic text-indigo-600 mix-blend-difference">{{ $metric['icon'] }}</i></span></div><div class="relative mt-4 text-xs font-black opacity-0 transition group-hover:opacity-70">Open details →</div></a>
                @endforeach
            </div>

            <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-200/60 dark:border-slate-700 dark:bg-slate-800 dark:shadow-none">
                <div class="flex flex-col gap-2 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6 dark:border-slate-700"><div><div class="text-xs font-black uppercase tracking-[.16em] text-indigo-600 dark:text-indigo-300">Land utilization</div><h3 class="mt-1 text-xl font-black text-slate-950 dark:text-white">Project inventory</h3></div><a href="{{ route('projects.index') }}" class="text-sm font-black text-indigo-600 dark:text-indigo-300">Manage projects →</a></div>
                <div class="grid gap-4 p-5 md:grid-cols-2 lg:grid-cols-3 sm:p-6">
                    @forelse($inventory as $project)
                        @php($used = (float) $project->saleable_area_marla > 0 ? min(100, ((float) $project->sold_area_marla + (float) $project->reserved_area_marla) / (float) $project->saleable_area_marla * 100) : 0)
                        <div class="group rounded-2xl border border-slate-200 bg-gradient-to-br from-white to-slate-50 p-5 transition hover:border-indigo-200 hover:shadow-lg dark:border-slate-700 dark:from-slate-800 dark:to-slate-900"><div class="flex items-start justify-between gap-4"><div><div class="font-black text-slate-950 dark:text-white">{{ $project->name }}</div><div class="mt-1 text-xs text-slate-500 dark:text-slate-400">{{ $project->location }}</div></div><a href="{{ route('sales.create', ['project' => $project->id]) }}" class="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-black text-indigo-700 hover:bg-indigo-600 hover:text-white dark:bg-indigo-950 dark:text-indigo-300">Book plot</a></div><div class="mt-5 flex items-end justify-between"><div><div class="text-2xl font-black text-slate-900 dark:text-white">{{ number_format($used, 1) }}%</div><div class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Utilized</div></div><div class="text-right text-xs text-slate-500"><b class="block text-sm text-emerald-600 dark:text-emerald-400">{{ number_format($project->available_area_marla / 20, 2) }} kanal</b>available</div></div><div class="mt-4 h-2.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-700"><div class="h-full rounded-full bg-gradient-to-r from-indigo-600 via-violet-500 to-fuchsia-500 shadow-sm" style="width: {{ $used }}%"></div></div><div class="mt-3 flex justify-between text-[11px] text-slate-500"><span>{{ number_format($project->sold_area_marla / 20, 2) }} kanal sold</span><span>{{ number_format($project->reserved_area_marla / 20, 2) }} reserved</span></div></div>
                    @empty<div class="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500 md:col-span-2 lg:col-span-3">No projects found for this scope.</div>@endforelse
                </div>
            </section>

            <div class="grid gap-6 lg:grid-cols-2">
                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-200/60 dark:border-slate-700 dark:bg-slate-800 dark:shadow-none"><div class="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-700"><div><div class="text-xs font-black uppercase tracking-wider text-violet-600 dark:text-violet-300">Sales activity</div><h3 class="mt-1 font-black text-slate-950 dark:text-white">Recent bookings</h3></div><a href="{{ route('bookings.index') }}" class="text-xs font-black text-indigo-600 dark:text-indigo-300">View all →</a></div><div class="divide-y divide-slate-100 dark:divide-slate-700">@forelse($recentBookings as $booking)<a href="{{ route('bookings.show', $booking) }}" class="group flex items-center gap-3 p-4 transition hover:bg-indigo-50/60 dark:hover:bg-slate-700/60"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-violet-100 font-black text-violet-700 dark:bg-violet-950 dark:text-violet-300">{{ strtoupper(substr($booking->customer->name, 0, 1)) }}</span><div class="min-w-0 flex-1"><div class="truncate font-bold text-slate-900 dark:text-white">{{ $booking->customer->name }}</div><div class="truncate text-xs text-slate-500 dark:text-slate-400">{{ $booking->project->name }} · {{ $booking->package->name }} · {{ $booking->agent?->referral_code ?? 'Direct' }}</div></div><div class="text-right"><div class="font-black text-slate-900 dark:text-white">Rs {{ number_format($booking->total_price) }}</div><div class="text-xs text-slate-400">{{ $booking->booking_date->format('d M Y') }}</div></div></a>@empty<div class="p-10 text-center text-sm text-slate-400">No bookings yet.</div>@endforelse</div></section>
                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-200/60 dark:border-slate-700 dark:bg-slate-800 dark:shadow-none"><div class="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-700"><div><div class="text-xs font-black uppercase tracking-wider text-emerald-600 dark:text-emerald-300">Collection activity</div><h3 class="mt-1 font-black text-slate-950 dark:text-white">Recent payments</h3></div><a href="{{ route('payments.index') }}" class="text-xs font-black text-indigo-600 dark:text-indigo-300">View all →</a></div><div class="divide-y divide-slate-100 dark:divide-slate-700">@forelse($recentPayments as $payment)<a href="{{ route('payments.edit', $payment) }}" class="group flex items-center gap-3 p-4 transition hover:bg-emerald-50/60 dark:hover:bg-slate-700/60"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl {{ $payment->status === 'verified' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300' }} font-black">{{ $payment->status === 'verified' ? '✓' : '⌛' }}</span><div class="min-w-0 flex-1"><div class="truncate font-bold text-slate-900 dark:text-white">{{ $payment->customer->name }}</div><div class="truncate font-mono text-xs text-slate-500 dark:text-slate-400">{{ $payment->receipt_number }} · {{ ucwords(str_replace('_', ' ', $payment->payment_method)) }}</div></div><div class="text-right"><div class="font-black {{ $payment->status === 'verified' ? 'text-emerald-700 dark:text-emerald-400' : 'text-amber-700 dark:text-amber-400' }}">Rs {{ number_format($payment->amount) }}</div><div class="text-xs text-slate-400">{{ $payment->payment_date->format('d M Y') }}</div></div></a>@empty<div class="p-10 text-center text-sm text-slate-400">No payments yet.</div>@endforelse</div></section>
            </div>
        </div>
    </div>
</x-app-layout>
