<x-app-layout>
    <div class="min-h-screen bg-white py-6 dark:bg-slate-950 sm:py-8">
        <div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6">
            <section class="management-command-pattern relative isolate overflow-hidden rounded-3xl p-5 text-slate-950 shadow-xl shadow-slate-200/60 sm:p-6">
                <div class="absolute inset-y-0 left-0 w-1.5 bg-black"></div>
                <div class="absolute -left-20 -bottom-24 h-48 w-48 rounded-full bg-indigo-100/50 blur-3xl"></div>
                <div class="absolute -right-20 -top-24 h-64 w-64 rounded-full border-[44px] border-gray-100/70"></div>
                <div class="relative">
                    <div class="flex flex-col gap-3 border-b border-slate-300/60 pb-4 sm:flex-row sm:items-center sm:justify-between">
                        <div class="flex items-center gap-3">
                            <span class="grid h-10 w-10 place-items-center rounded-xl bg-black text-sm font-black text-white shadow-lg shadow-indigo-200">M</span>
                            <div><div class="text-[10px] font-black uppercase tracking-[.2em] text-Slate-700">Management command center</div><div class="mt-0.5 flex items-center gap-1.5 text-xs font-bold text-slate-500"><span class="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]"></span>Live business overview</div></div>
                        </div>
                        <a href="{{ route('sales.create', ['project' => $projectId]) }}" class="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-black px-4 py-2.5 text-xs font-black text-white shadow-lg shadow-black transition hover:-translate-y-0.5 hover:bg-indigo-800 sm:w-auto"><span class="text-base leading-none">+</span> New booking</a>
                    </div>
                    <div class="grid gap-5 pt-5 lg:grid-cols-[minmax(0,1fr)_310px] lg:items-center">
                        <div class="min-w-0">
                            <div class="admin-command-badge inline-flex items-center gap-2 rounded-lg px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em]"><span>◆</span> Business dashboard</div>
                            <h3 class="mt-3 max-w-4xl text-3xl font-black leading-tight tracking-[-.035em] text-slate-950 sm:text-4xl lg:whitespace-nowrap">Welcome back, {{ auth()->user()->name }}.</h3>
                            <p class="mt-3 max-w-2xl text-sm leading-5 text-slate-500">Sales, collections, inventory and commissions—organized in one clear operational view.</p>
                        </div>
                        <form method="GET" class="rounded-2xl border border-slate-100 bg-gradient-to-br from-slate-50 via-white to-slate-50 p-4 shadow-sm lg:ml-1">
                            <div class="mb-3 flex items-center justify-between"><div><div class="text-[10px] font-black uppercase tracking-[.18em] text-slate-900">Dashboard scope</div><div class="mt-1 text-[11px] text-slate-500">Filter the complete overview</div></div><span class="grid h-8 w-8 place-items-center rounded-lg bg-slate-800 text-white shadow-md shadow-slate-200">⌄</span></div>
                            <label class="block">
                                <select name="project" onchange="this.form.submit()" class="mt-2 w-full rounded-xl border-slate-200 bg-white text-sm font-bold text-slate-800 focus:border-indigo-500 focus:ring-indigo-500">
                                    <option value="">All projects</option>
                                    @foreach($projects as $project)<option value="{{ $project->id }}" @selected($projectId == $project->id)>{{ $project->name }}</option>@endforeach
                                </select>
                            </label>
                            <div class="mt-3 flex items-center gap-1.5 text-[10px] font-medium text-slate-500"><span class="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_7px_#34d399]"></span>Updated {{ now()->format('d M Y, h:i A') }}</div>
                        </form>
                    </div>
                </div>
            </section>

            <section>
                <div class="mb-4 flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between">
                    <div><div class="text-[10px] font-black uppercase tracking-[.2em] text-slate-600">Business pulse</div><h2 class="mt-1 text-2xl font-black tracking-tight text-slate-950 dark:text-white">Operational overview</h2></div>
                    <p class="text-xs text-slate-400">Live totals for the selected dashboard scope</p>
                </div>
                <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                @php($metrics = [
                    ['label' => 'Verified receipts', 'value' => 'Rs '.number_format($received), 'note' => 'Successfully collected', 'icon' => '✓', 'accent' => 'bg-slate-800 text-white', 'bar' => 'bg-slate-900', 'tint' => 'bg-slate-50/70 dark:bg-slate-950/30', 'link' => route('payments.index', ['status' => 'verified', 'project' => $projectId])],
                    ['label' => 'Active bookings', 'value' => number_format($activeBookings), 'note' => 'Approved and active plans', 'icon' => '#', 'accent' => 'bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-300', 'bar' => 'bg-violet-500', 'tint' => 'bg-violet-50/70 dark:bg-violet-950/25', 'link' => route('bookings.index', ['project' => $projectId])],
                    ['label' => 'Outstanding', 'value' => 'Rs '.number_format($outstanding), 'note' => 'Remaining installment value', 'icon' => '↗', 'accent' => 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300', 'bar' => 'bg-amber-500', 'tint' => 'bg-amber-50/70 dark:bg-amber-950/25', 'link' => route('installments.index', ['project' => $projectId])],
                    ['label' => 'Overdue', 'value' => 'Rs '.number_format($overdue), 'note' => 'Requires collection follow-up', 'icon' => '!', 'accent' => 'bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300', 'bar' => 'bg-rose-500', 'tint' => 'bg-rose-50/70 dark:bg-rose-950/25', 'link' => route('installments.index', ['status' => 'overdue', 'project' => $projectId])],
                    ['label' => 'Payable commission', 'value' => 'Rs '.number_format($payableCommission), 'note' => 'Earned and awaiting payout', 'icon' => '%', 'accent' => 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300', 'bar' => 'bg-emerald-500', 'tint' => 'bg-emerald-50/70 dark:bg-emerald-950/25', 'link' => route('customers.index', ['type' => 'agent'])],
                    ['label' => 'Available land', 'value' => number_format($availableMarla / 20, 2).' kanal', 'note' => 'Ready across selected projects', 'icon' => '◇', 'accent' => 'bg-cyan-100 text-cyan-700 dark:bg-cyan-950 dark:text-cyan-300', 'bar' => 'bg-cyan-500', 'tint' => 'bg-cyan-50/70 dark:bg-cyan-950/25', 'link' => route('projects.index')],
                ])
                @foreach($metrics as $metric)
                    <a href="{{ $metric['link'] }}" class="group relative overflow-hidden rounded-2xl border border-slate-200 p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-xl dark:border-slate-700 {{ $metric['tint'] }}"><span class="absolute inset-y-0 left-0 w-1 {{ $metric['bar'] }}"></span><div class="flex items-start justify-between gap-4"><div class="min-w-0"><div class="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">{{ $metric['label'] }}</div><div class="mt-3 break-words text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">{{ $metric['value'] }}</div><div class="mt-2 text-xs font-medium text-slate-400">{{ $metric['note'] }}</div></div><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl text-lg font-black {{ $metric['accent'] }}">{{ $metric['icon'] }}</span></div><div class="mt-4 flex items-center justify-between border-t border-white/70 pt-3 text-[10px] font-black uppercase tracking-wider text-slate-600 dark:border-white/10 dark:text-slate-300"><span>Open details</span><span class="transition group-hover:translate-x-1">→</span></div></a>
                @endforeach
                </div>
            </section>

            <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900">
                <div class="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6 dark:border-slate-800"><div class="flex items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 font-black text-slate-700 dark:bg-slate-950 dark:text-slate-300">◇</span><div><div class="text-[10px] font-black uppercase tracking-[.18em] text-slate-600 dark:text-slate-300">Land utilization</div><h3 class="mt-1 text-xl font-black text-slate-950 dark:text-white">Project inventory</h3></div></div><a href="{{ route('projects.index') }}" class="inline-flex items-center justify-center rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-black text-slate-700 transition hover:border-slate-300 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300">Manage projects →</a></div>
                <div class="grid gap-4 p-5 md:grid-cols-2 lg:grid-cols-3 sm:p-6">
                    @forelse($inventory as $project)
                        @php($used = (float) $project->saleable_area_marla > 0 ? min(100, ((float) $project->sold_area_marla + (float) $project->reserved_area_marla) / (float) $project->saleable_area_marla * 100) : 0)
                        <div class="group rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-indigo-300 hover:shadow-lg dark:border-slate-700 dark:bg-slate-950/40"><div class="flex items-start justify-between gap-4"><div class="min-w-0"><div class="truncate font-black text-slate-950 dark:text-white">{{ $project->name }}</div><div class="mt-1 truncate text-xs text-slate-500 dark:text-slate-400">{{ $project->location }}</div></div><a href="{{ route('sales.create', ['project' => $project->id]) }}" class="shrink-0 rounded-lg bg-slate-800 px-3 py-2 text-xs font-black text-white hover:bg-slate-800">Book plot</a></div><div class="mt-5 flex items-end justify-between"><div><div class="text-2xl font-black text-slate-900 dark:text-white">{{ number_format($used, 1) }}%</div><div class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Utilized</div></div><div class="text-right text-xs text-slate-500"><b class="block text-sm text-emerald-600 dark:text-emerald-400">{{ number_format($project->available_area_marla / 20, 2) }} kanal</b>available</div></div><div class="mt-4 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-700"><div class="h-full rounded-full bg-indigo-600" style="width: {{ $used }}%"></div></div><div class="mt-3 flex justify-between gap-3 text-[11px] text-slate-500"><span>{{ number_format($project->sold_area_marla / 20, 2) }} kanal sold</span><span class="text-right">{{ number_format($project->reserved_area_marla / 20, 2) }} reserved</span></div></div>
                    @empty<div class="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500 md:col-span-2 lg:col-span-3">No projects found for this scope.</div>@endforelse
                </div>
            </section>

            <div class="grid gap-6 lg:grid-cols-2">
                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-800"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 font-black text-violet-700 dark:bg-violet-950 dark:text-violet-300">#</span><div><div class="text-[10px] font-black uppercase tracking-wider text-violet-600 dark:text-violet-300">Sales activity</div><h3 class="mt-1 font-black text-slate-950 dark:text-white">Recent bookings</h3></div></div><a href="{{ route('bookings.index') }}" class="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-black text-indigo-600 dark:border-slate-700 dark:text-indigo-300">View all →</a></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($recentBookings as $booking)<a href="{{ route('bookings.show', $booking) }}" class="group flex items-center gap-3 p-4 transition hover:bg-indigo-50/60 dark:hover:bg-slate-800"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-violet-100 font-black text-violet-700 dark:bg-violet-950 dark:text-violet-300">{{ strtoupper(substr($booking->customer->name, 0, 1)) }}</span><div class="min-w-0 flex-1"><div class="truncate font-bold text-slate-900 dark:text-white">{{ $booking->customer->name }}</div><div class="truncate text-xs text-slate-500 dark:text-slate-400">{{ $booking->project->name }} · {{ $booking->package->name }} · {{ $booking->agent?->referral_code ?? 'Direct' }}</div></div><div class="shrink-0 text-right"><div class="font-black text-slate-900 dark:text-white">Rs {{ number_format($booking->total_price) }}</div><div class="text-xs text-slate-400">{{ $booking->booking_date->format('d M Y') }}</div></div></a>@empty<div class="p-10 text-center text-sm text-slate-400">No bookings yet.</div>@endforelse</div></section>
                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div class="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-800"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-100 font-black text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">Rs</span><div><div class="text-[10px] font-black uppercase tracking-wider text-emerald-600 dark:text-emerald-300">Collection activity</div><h3 class="mt-1 font-black text-slate-950 dark:text-white">Recent payments</h3></div></div><a href="{{ route('payments.index') }}" class="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-black text-indigo-600 dark:border-slate-700 dark:text-indigo-300">View all →</a></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($recentPayments as $payment)<a href="{{ route('payments.edit', $payment) }}" class="group flex items-center gap-3 p-4 transition hover:bg-emerald-50/60 dark:hover:bg-slate-800"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl {{ $payment->status === 'verified' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300' }} font-black">{{ $payment->status === 'verified' ? '✓' : '⌛' }}</span><div class="min-w-0 flex-1"><div class="truncate font-bold text-slate-900 dark:text-white">{{ $payment->customer->name }}</div><div class="truncate font-mono text-xs text-slate-500 dark:text-slate-400">{{ $payment->receipt_number }} · {{ ucwords(str_replace('_', ' ', $payment->payment_method)) }}</div></div><div class="shrink-0 text-right"><div class="font-black {{ $payment->status === 'verified' ? 'text-emerald-700 dark:text-emerald-400' : 'text-amber-700 dark:text-amber-400' }}">Rs {{ number_format($payment->amount) }}</div><div class="text-xs text-slate-400">{{ $payment->payment_date->format('d M Y') }}</div></div></a>@empty<div class="p-10 text-center text-sm text-slate-400">No payments yet.</div>@endforelse</div></section>
            </div>
        </div>
    </div>
</x-app-layout>
