<section class="overflow-hidden rounded-3xl border border-indigo-100 bg-white shadow-xl shadow-indigo-100/50 dark:border-gray-700 dark:bg-gray-800">
    <div class="border-b border-indigo-100 bg-gradient-to-r from-indigo-950 via-indigo-800 to-violet-700 p-6 text-white">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div class="text-[10px] font-black uppercase tracking-[.2em] text-indigo-200">Encrypted database settings</div><h3 class="mt-1 text-xl font-black">Online payment gateways</h3><p class="mt-1 text-xs text-indigo-100">Credentials are encrypted with the application key and are never displayed after saving.</p></div><span class="w-fit rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs font-black">JazzCash · Easypaisa · Binance Pay</span></div>
    </div>
    <div class="grid gap-5 p-5 lg:grid-cols-2 xl:grid-cols-3">
        @foreach(['jazzcash' => ['JazzCash','from-orange-500 to-rose-600','merchant_id','Merchant ID'], 'easypaisa' => ['Easypaisa','from-emerald-500 to-teal-700','store_id','Store ID'], 'binance' => ['Binance Pay','from-amber-400 to-yellow-600','merchant_id','Merchant ID']] as $provider => $meta)
            @php($gateway = $gateways[$provider])
            @php($credentials = $gateway->credentials ?? [])
            <form method="POST" action="{{ route('payment-gateways.update', $provider) }}" class="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50/60 dark:border-slate-700 dark:bg-slate-900">@csrf @method('PUT')
                <div class="flex items-center justify-between bg-gradient-to-r {{ $meta[1] }} p-4 text-white"><div><h4 class="font-black">{{ $meta[0] }}</h4><span class="text-[10px] font-semibold text-white/80">{{ $gateway->isComplete() ? 'Credentials complete' : 'Setup required' }}</span></div><span class="rounded-full px-2.5 py-1 text-[9px] font-black {{ $gateway->enabled ? 'bg-white text-emerald-700' : 'bg-black/15 text-white' }}">{{ $gateway->enabled ? 'ENABLED' : 'DISABLED' }}</span></div>
                <div class="space-y-4 p-4">
                    <div class="grid grid-cols-2 gap-3">
                        <label class="text-xs font-black uppercase tracking-wide text-slate-500">Mode<select name="mode" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm dark:border-slate-600 dark:bg-slate-800 dark:text-white"><option value="sandbox" @selected($gateway->mode === 'sandbox')>Sandbox</option><option value="live" @selected($gateway->mode === 'live')>Live</option></select></label>
                        <label class="flex items-end gap-2 pb-3 text-sm font-bold text-slate-700 dark:text-slate-200"><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" @checked($gateway->enabled) class="rounded border-slate-300 text-indigo-600"> Enable gateway</label>
                    </div>
                    <label class="block text-xs font-black uppercase tracking-wide text-slate-500">{{ $meta[3] }}<input name="{{ $meta[2] }}" autocomplete="off" placeholder="{{ filled($credentials[$meta[2]] ?? null) ? 'Saved securely · enter to replace' : 'Required' }}" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"></label>
                    @if($provider === 'jazzcash')
                        <div class="grid gap-3 sm:grid-cols-2"><label class="text-xs font-black uppercase tracking-wide text-slate-500">Password<input type="password" name="password" autocomplete="new-password" placeholder="{{ filled($credentials['password'] ?? null) ? 'Saved securely' : 'Required' }}" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"></label><label class="text-xs font-black uppercase tracking-wide text-slate-500">Integrity salt<input type="password" name="integrity_salt" autocomplete="new-password" placeholder="{{ filled($credentials['integrity_salt'] ?? null) ? 'Saved securely' : 'Required' }}" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"></label></div>
                    @elseif($provider === 'easypaisa')
                        <label class="block text-xs font-black uppercase tracking-wide text-slate-500">Hash key<input type="password" name="hash_key" autocomplete="new-password" placeholder="{{ filled($credentials['hash_key'] ?? null) ? 'Saved securely · enter to replace' : 'Required' }}" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"></label>
                    @else
                        <div class="grid gap-3 sm:grid-cols-2"><label class="text-xs font-black uppercase tracking-wide text-slate-500">API key<input type="password" name="api_key" autocomplete="new-password" placeholder="{{ filled($credentials['api_key'] ?? null) ? 'Saved securely' : 'Required' }}" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"></label><label class="text-xs font-black uppercase tracking-wide text-slate-500">Secret key<input type="password" name="secret_key" autocomplete="new-password" placeholder="{{ filled($credentials['secret_key'] ?? null) ? 'Saved securely' : 'Required' }}" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"></label></div>
                    @endif
                    <label class="block text-xs font-black uppercase tracking-wide text-slate-500">Gateway API / checkout URL<input type="url" name="api_url" value="{{ $gateway->api_url }}" required class="mt-1.5 w-full rounded-xl border-slate-300 text-sm normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white" placeholder="https://"></label>
                    <label class="block text-xs font-black uppercase tracking-wide text-slate-500">Return URL<input type="url" name="return_url" value="{{ $gateway->return_url ?: route('dashboard') }}" required class="mt-1.5 w-full rounded-xl border-slate-300 text-sm normal-case dark:border-slate-600 dark:bg-slate-800 dark:text-white"></label>
                    <button class="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white transition hover:bg-indigo-700 dark:bg-indigo-600">Save encrypted settings</button>
                </div>
            </form>
        @endforeach
    </div>
</section>
