<x-app-layout>
    <div class="min-h-screen via-slate-50 to-white py-6 dark:from-slate-950 dark:via-slate-900 dark:to-gray-950 sm:py-8">
        <div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6">
            <section class="admin-command-card admin-command-summary p-6 text-white shadow-2xl shadow-indigo-200 dark:shadow-none sm:p-8"><div class="absolute -right-16 -top-20 -z-10 h-64 w-64 rounded-full"></div><div class="absolute -bottom-24 left-1/3 -z-10 h-56 w-56 rounded-full"></div><div><span class="rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold text-indigo-100">Tamper-resistant history</span><h3 class="mt-5 text-3xl font-black tracking-tight">Every important change, accounted for.</h3><p class="mt-3 max-w-2xl text-sm leading-6 text-indigo-200">Review who created, updated, or deleted operational records, together with the exact values captured at that moment.</p></div><div class="admin-command-stat-grid mt-4 grid grid-cols-2 gap-2.5 lg:grid-cols-5">@foreach([['All activity',$summary['total'],'Complete history','bg-violet-400'],['Today',$summary['today'],'Recent events','bg-indigo-400'],['Created',$summary['created'],'New records','bg-emerald-400'],['Updated',$summary['updated'],'Changed records','bg-cyan-400'],['Deleted',$summary['deleted'],'Removed records','bg-rose-400']] as [$label,$value,$hint,$accent])<div class="admin-command-stat rounded-2xl border p-3.5 backdrop-blur sm:p-4"><div class="flex items-center gap-2 text-[9px] font-black uppercase tracking-wider text-indigo-200 sm:text-[10px]"><span class="h-2 w-2 rounded-full {{ $accent }}"></span>{{ $label }}</div><div class="mt-2 text-2xl font-black sm:text-3xl">{{ number_format($value) }}</div><div class="mt-1 text-[10px] text-indigo-100/65 sm:text-xs">{{ $hint }}</div></div>@endforeach</div></section>

            <form method="GET" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-lg shadow-slate-200/50 dark:border-slate-700 dark:bg-slate-800 dark:shadow-none"><div class="grid gap-3 md:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_auto]"><label class="text-[10px] font-black uppercase tracking-wider text-slate-500">Search actor or activity<input name="search" value="{{ request('search') }}" placeholder="Name, email, description…" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm font-normal normal-case tracking-normal dark:bg-slate-900"></label><label class="text-[10px] font-black uppercase tracking-wider text-slate-500">Record type<select name="log" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm font-normal normal-case dark:bg-slate-900"><option value="">All record types</option>@foreach($logNames as $name)<option value="{{ $name }}" @selected(request('log') === $name)>{{ $name }}</option>@endforeach</select></label><label class="text-[10px] font-black uppercase tracking-wider text-slate-500">Event<select name="event" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm font-normal normal-case dark:bg-slate-900"><option value="">All events</option>@foreach(['created','updated','deleted'] as $event)<option value="{{ $event }}" @selected(request('event') === $event)>{{ ucfirst($event) }}</option>@endforeach</select></label><div class="flex items-end gap-2"><button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-black text-white shadow hover:bg-indigo-700">Filter</button><a href="{{ route('management.activity-log.index') }}" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-300">Clear</a></div></div></form>

            <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-200/60 dark:border-slate-700 dark:bg-slate-800 dark:shadow-none">
                <div class="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-700"><div><h3 class="font-black text-slate-950 dark:text-white">Activity timeline</h3><p class="mt-1 text-xs text-slate-500">Newest events appear first</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600 dark:bg-slate-900 dark:text-slate-300">{{ $activities->total() }} result(s)</span></div>
                <div class="divide-y divide-slate-100 dark:divide-slate-700">
                    @forelse($activities as $activity)
                        @php($event = $activity->event ?? 'logged')
                        @php($eventStyle = match($event) {'created' => ['bg-emerald-100 text-emerald-700 ring-emerald-200','+'], 'deleted' => ['bg-rose-100 text-rose-700 ring-rose-200','−'], default => ['bg-blue-100 text-blue-700 ring-blue-200','↻']})
                        @php($attributes = $activity->properties['attributes'] ?? [])
                        @php($old = $activity->properties['old'] ?? [])
                        <article x-data="{ open: false }" class="relative p-4 transition hover:bg-slate-50/70 dark:hover:bg-slate-900/40 sm:p-5"><div class="flex items-start gap-4"><span class="relative z-10 grid h-11 w-11 shrink-0 place-items-center rounded-xl font-black ring-4 {{ $eventStyle[0] }}">{{ $eventStyle[1] }}</span><div class="min-w-0 flex-1"><div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><b class="text-sm text-slate-950 dark:text-white">{{ $activity->causer?->name ?? 'System process' }}</b><span class="rounded-full px-2 py-0.5 text-[10px] font-black uppercase {{ $event === 'created' ? 'bg-emerald-100 text-emerald-700' : ($event === 'deleted' ? 'bg-rose-100 text-rose-700' : 'bg-blue-100 text-blue-700') }}">{{ $event }}</span><span class="rounded-full bg-violet-50 px-2 py-0.5 text-[10px] font-bold text-violet-700 dark:bg-violet-950 dark:text-violet-300">{{ $activity->log_name }}</span></div><p class="mt-1 text-sm text-slate-600 dark:text-slate-300"><b>{{ $activity->log_name }}</b> record <span class="font-mono text-xs text-slate-400">#{{ $activity->subject_id ?? '—' }}</span> was {{ $event }}.</p><div class="mt-1 text-[11px] text-slate-400">{{ $activity->causer?->email ?? 'Automated system activity' }}</div></div><div class="shrink-0 text-left sm:text-right"><div class="text-xs font-bold text-slate-600 dark:text-slate-300">{{ $activity->created_at->format('d M Y') }}</div><div class="text-[10px] text-slate-400">{{ $activity->created_at->format('h:i:s A') }} · {{ $activity->created_at->diffForHumans() }}</div></div></div>
                                @if($attributes || $old)<button type="button" @click="open=!open" class="mt-3 inline-flex items-center gap-1 rounded-lg bg-slate-100 px-3 py-1.5 text-[11px] font-black text-slate-600 hover:bg-indigo-100 hover:text-indigo-700 dark:bg-slate-900 dark:text-slate-300"><span x-text="open ? 'Hide changes' : 'View changes'">View changes</span><span x-text="open ? '↑' : '↓'">↓</span></button><div x-show="open" x-cloak class="mt-3 overflow-hidden rounded-xl border border-slate-200 dark:border-slate-700"><div class="grid bg-slate-50 px-3 py-2 text-[10px] font-black uppercase tracking-wider text-slate-500 dark:bg-slate-900 sm:grid-cols-[180px_1fr_1fr]"><span>Field</span><span class="hidden sm:block">Previous value</span><span class="hidden sm:block">New value</span></div><div class="divide-y divide-slate-100 dark:divide-slate-700">@foreach($attributes as $key => $value)<div class="grid gap-1 px-3 py-2.5 text-xs sm:grid-cols-[180px_1fr_1fr]"><b class="text-slate-700 dark:text-slate-200">{{ str($key)->headline() }}</b><div><span class="sm:hidden font-bold text-slate-400">Before: </span><span class="break-all text-rose-600">{{ array_key_exists($key,$old) ? (is_scalar($old[$key]) || is_null($old[$key]) ? ($old[$key] ?? 'null') : json_encode($old[$key])) : '—' }}</span></div><div><span class="sm:hidden font-bold text-slate-400">After: </span><span class="break-all text-emerald-700 dark:text-emerald-400">{{ is_scalar($value) || is_null($value) ? ($value ?? 'null') : json_encode($value) }}</span></div></div>@endforeach</div></div>@endif
                            </div></div></article>
                    @empty<div class="p-16 text-center"><div class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-100 text-2xl text-slate-400 dark:bg-slate-900">⌕</div><h3 class="mt-4 font-black text-slate-800 dark:text-white">No activity found</h3><p class="mt-1 text-sm text-slate-400">Try clearing or changing the current filters.</p></div>@endforelse
                </div>
                @if($activities->hasPages())<div class="border-t border-slate-100 p-4 dark:border-slate-700">{{ $activities->links() }}</div>@endif
            </section>
        </div>
    </div>
</x-app-layout>
