<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between gap-4"><div><h2 class="text-xl font-semibold text-gray-800">Staff management</h2><p class="mt-1 text-sm text-gray-500">Create and manage office staff accounts.</p></div><a href="{{ route('staff.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Add staff</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-5 px-4">
        @if(session('success'))<div class="rounded-lg bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        <form class="flex gap-3 rounded-xl bg-white p-4 shadow-sm"><input name="search" value="{{ request('search') }}" placeholder="Name, referral code, CNIC, email or phone" class="min-w-0 flex-1 rounded-lg border-gray-300"><button class="rounded-lg bg-indigo-600 px-5 py-2 font-semibold text-white">Search</button>@if(request()->filled('search'))<a href="{{ route('staff.index') }}" class="rounded-lg border px-5 py-2 text-gray-600">Clear</a>@endif</form>
        <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th class="p-4">Team member</th><th>Role</th><th>CNIC</th><th>Contact</th><th>Address</th><th>Status</th><th class="pr-4 text-right">Actions</th></tr></thead><tbody>
            @forelse($staff as $member) @php($roleStyle = match($member->role) {'super_admin' => 'bg-amber-100 text-amber-800 ring-1 ring-amber-200', 'admin' => 'bg-violet-100 text-violet-700', default => 'bg-blue-100 text-blue-700'}) @php($roleLabel = match($member->role) {'super_admin' => 'Super Admin', 'admin' => 'Administrator', default => 'Staff'})<tr class="border-t align-top"><td class="p-4"><div class="font-semibold">{{ $member->name }}</div><div class="mt-1 text-xs text-gray-500">S/O {{ $member->father_name ?: '—' }}</div><div class="mt-1 font-mono text-xs font-semibold text-indigo-600">{{ $member->referral_code ?: '—' }}</div></td><td class="py-4"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $roleStyle }}">{{ $roleLabel }}</span></td><td class="py-4">{{ $member->cnic ?: '—' }}</td><td class="py-4"><div>{{ $member->email }}</div><div class="mt-1 text-xs text-gray-500">{{ $member->phone ?: '—' }}</div></td><td class="max-w-xs py-4 text-gray-600">{{ $member->address ?: '—' }}</td><td class="py-4"><span class="rounded-full px-2 py-1 text-xs {{ $member->status ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600' }}">{{ $member->status ? 'Active' : 'Inactive' }}</span></td><td class="pr-4 pt-4"><div class="flex justify-end gap-3">@if($member->role !== 'super_admin' || auth()->user()->role === 'super_admin')<a href="{{ route('staff.edit', $member) }}" class="font-medium text-indigo-600">Edit</a>@endif @unless($member->is(auth()->user()) || $member->role === 'super_admin')<form method="POST" action="{{ route('staff.destroy', $member) }}" onsubmit="return confirm('Delete this management account?')">@csrf @method('DELETE')<button class="text-red-600">Delete</button></form>@endunless</div></td></tr>
            @empty<tr><td colspan="7" class="p-10 text-center text-gray-500">No management accounts found.</td></tr>@endforelse
        </tbody></table></div>{{ $staff->links() }}
    </div></div>
</x-app-layout>
