<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-semibold text-gray-800 dark:text-white">Staff management</h2><p class="mt-1 text-sm text-gray-500 dark:text-slate-400">Create and manage office staff accounts.</p></div><a href="{{ route('staff.create') }}" class="inline-flex w-full items-center justify-center rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white sm:w-auto">Add staff</a></div></x-slot>
    <div class="py-5 sm:py-8"><div class="mx-auto max-w-7xl space-y-5 px-3 sm:px-4">
        @if(session('success'))<div class="rounded-lg bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        <form class="grid gap-3 rounded-xl bg-white p-4 shadow-sm sm:grid-cols-[1fr_auto_auto] dark:bg-slate-800"><input name="search" value="{{ request('search') }}" placeholder="Name, referral code, CNIC, email or phone" class="min-w-0 rounded-lg border-gray-300 dark:border-slate-600 dark:bg-slate-900 dark:text-white"><button class="rounded-lg bg-indigo-600 px-5 py-2.5 font-semibold text-white">Search</button>@if(request()->filled('search'))<a href="{{ route('staff.index') }}" class="rounded-lg border px-5 py-2.5 text-center text-gray-600 dark:border-slate-600 dark:text-slate-300">Clear</a>@endif</form>
        <div class="rounded-xl bg-white shadow-sm dark:bg-slate-800"><table class="admin-responsive-table w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500 dark:bg-slate-900 dark:text-slate-300"><tr><th class="p-4">Team member</th><th>Role</th><th>CNIC</th><th>Contact</th><th>Address</th><th>Status</th><th class="pr-4 text-right">Actions</th></tr></thead><tbody>
            @forelse($staff as $member) @php($roleStyle = match($member->role) {'super_admin' => 'bg-amber-100 text-amber-800 ring-1 ring-amber-200', 'admin' => 'bg-violet-100 text-violet-700', 'booking' => 'bg-cyan-100 text-cyan-700', 'verification' => 'bg-emerald-100 text-emerald-700', 'withdrawal' => 'bg-orange-100 text-orange-700', default => 'bg-blue-100 text-blue-700'}) @php($roleLabel = match($member->role) {'super_admin' => 'Super Admin', 'admin' => 'Administrator', 'booking' => 'Booking', 'verification' => 'Verification', 'withdrawal' => 'Withdrawal', default => 'Staff'})<tr class="border-t align-top dark:border-slate-700 dark:text-white"><td data-label="Team member" class="p-4"><span><b class="block font-semibold">{{ $member->name }}</b><small class="mt-1 block text-xs text-gray-500 dark:text-slate-400">S/O {{ $member->father_name ?: '—' }}</small><small class="mt-1 block font-mono text-xs font-semibold text-indigo-600 dark:text-indigo-300">{{ $member->referral_code ?: '—' }}</small></span></td><td data-label="Role" class="py-4"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $roleStyle }}">{{ $roleLabel }}</span></td><td data-label="CNIC" class="py-4">{{ $member->cnic ?: '—' }}</td><td data-label="Contact" class="py-4"><span class="min-w-0 break-all">{{ $member->email }}<small class="mt-1 block text-xs text-gray-500 dark:text-slate-400">{{ $member->phone ?: '—' }}</small></span></td><td data-label="Address" class="max-w-xs py-4 text-gray-600 dark:text-slate-300">{{ $member->address ?: '—' }}</td><td data-label="Status" class="py-4"><span class="rounded-full px-2 py-1 text-xs {{ $member->status ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600' }}">{{ $member->status ? 'Active' : 'Inactive' }}</span></td><td data-label="Actions" class="pr-4 pt-4"><div class="flex w-full justify-end gap-3">@if($member->role !== 'super_admin' || auth()->user()->hasRole('super_admin'))<a href="{{ route('staff.edit', $member) }}" class="flex-1 rounded-lg bg-indigo-600 px-4 py-2 text-center font-bold text-white sm:flex-none">Edit</a>@endif @unless($member->is(auth()->user()) || $member->role === 'super_admin')<form method="POST" action="{{ route('staff.destroy', $member) }}" class="flex-1 sm:flex-none" onsubmit="return confirm('Delete this management account?')">@csrf @method('DELETE')<button class="w-full rounded-lg bg-red-50 px-4 py-2 font-bold text-red-600">Delete</button></form>@endunless</div></td></tr>
            @empty<tr><td colspan="7" class="p-10 text-center text-gray-500">No management accounts found.</td></tr>@endforelse
        </tbody></table></div>{{ $staff->links() }}
    </div></div>
</x-app-layout>
