@csrf
@if(isset($plot)) @method('PUT') @endif
<div x-data="{ project: '{{ old('project_id', $plot->project_id ?? request('project')) }}', block: '{{ old('block_id', $plot->block_id ?? '') }}' }" class="grid gap-5 sm:grid-cols-2">
    <label class="text-sm font-semibold text-gray-700">Project<select name="project_id" x-model="project" @change="block=''" required class="mt-1.5 w-full rounded-xl border-gray-300"><option value="">Select project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold text-gray-700">Block<select name="block_id" x-model="block" :disabled="!project" required class="mt-1.5 w-full rounded-xl border-gray-300 disabled:bg-gray-100"><option value="">Select block</option>@foreach($blocks as $block)<option x-show="project === '{{ $block->project_id }}'" value="{{ $block->id }}">{{ $block->name }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold text-gray-700">Plot number<input name="plot_number" value="{{ old('plot_number', $plot->plot_number ?? '') }}" maxlength="50" required class="mt-1.5 w-full rounded-xl border-gray-300"></label>
    <label class="text-sm font-semibold text-gray-700">Size (marla)<input type="number" name="size_marla" value="{{ old('size_marla', $plot->size_marla ?? '') }}" min="0.01" step="0.01" required class="mt-1.5 w-full rounded-xl border-gray-300"></label>
    <label class="text-sm font-semibold text-gray-700">Category<select name="category" required class="mt-1.5 w-full rounded-xl border-gray-300">@foreach(['residential'=>'Residential','commercial'=>'Commercial','farmhouse'=>'Farmhouse'] as $value=>$label)<option value="{{ $value }}" @selected(old('category', $plot->category ?? 'residential')===$value)>{{ $label }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold text-gray-700">Status<select name="status" required class="mt-1.5 w-full rounded-xl border-gray-300">@foreach(['available','held','reserved','booked','sold','blocked','disputed'] as $value)<option value="{{ $value }}" @selected(old('status', isset($plot) ? $plot->status->value : 'available')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold text-gray-700">Base price (Rs)<input type="number" name="base_price" value="{{ old('base_price', $plot->base_price ?? 0) }}" min="0" step="0.01" required class="mt-1.5 w-full rounded-xl border-gray-300"></label>
    <label class="text-sm font-semibold text-gray-700">Premium (Rs)<input type="number" name="premium_amount" value="{{ old('premium_amount', $plot->premium_amount ?? 0) }}" min="0" step="0.01" class="mt-1.5 w-full rounded-xl border-gray-300"></label>
</div>
<div class="mt-7 flex gap-3"><button class="rounded-xl bg-indigo-600 px-5 py-3 font-black text-white hover:bg-indigo-700">{{ isset($plot) ? 'Save changes' : 'Create plot' }}</button><a href="{{ route('plots.index') }}" class="rounded-xl border border-gray-300 px-5 py-3 font-bold text-gray-700">Cancel</a></div>
