<x-app-layout>
    <x-slot name="header"><div><h2 class="text-xl font-black text-gray-900">Review detected inventory</h2><p class="text-sm text-gray-500">{{ $project->name }} · Nothing has been imported yet</p></div></x-slot>
    @php($plotCount=collect($analysis['blocks'])->sum(fn($block)=>count($block['plots'])))
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-5 px-4">
        @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{{ $errors->first() }}</div>@endif
        <section class="grid gap-4 sm:grid-cols-3"><div class="rounded-xl bg-indigo-700 p-5 text-white"><div class="text-xs font-bold uppercase text-indigo-200">Detected</div><div class="mt-1 text-3xl font-black">{{ $plotCount }} plots</div></div><div class="rounded-xl bg-white p-5 ring-1 ring-gray-200"><div class="text-xs font-bold uppercase text-gray-400">Groups / blocks</div><div class="mt-1 text-3xl font-black">{{ count($analysis['blocks']) }}</div></div><div class="rounded-xl bg-white p-5 ring-1 ring-gray-200"><div class="text-xs font-bold uppercase text-gray-400">Result</div><p class="mt-2 text-sm text-gray-700">{{ $analysis['summary'] }}</p></div></section>
        @if($analysis['warnings'])<section class="rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 class="font-black text-amber-900">Check these items carefully</h3><ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-800">@foreach($analysis['warnings'] as $warning)<li>{{ $warning }}</li>@endforeach</ul></section>@endif
        <form method="POST" action="{{ route('projects.plot-plan.store',$project) }}" class="space-y-5">@csrf
            <input type="hidden" name="token" value="{{ $analysis['token'] }}">
            <div class="grid gap-4 rounded-xl bg-white p-5 ring-1 ring-gray-200 sm:grid-cols-2"><label class="text-sm font-bold">Category<select name="category" class="mt-1 w-full rounded-lg border-gray-300">@foreach(['residential','commercial','farmhouse'] as $category)<option value="{{ $category }}" @selected($analysis['category']===$category)>{{ ucfirst($category) }}</option>@endforeach</select></label><label class="text-sm font-bold">Price per marla (Rs)<input name="price_per_marla" type="number" min="0" step="0.01" value="{{ $analysis['price_per_marla'] }}" class="mt-1 w-full rounded-lg border-gray-300"></label></div>
            @foreach($analysis['blocks'] as $blockIndex=>$block)
                <section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-gray-200">
                    <div class="flex flex-col gap-3 border-b bg-gray-50 p-5 sm:flex-row sm:items-end sm:justify-between"><label class="flex-1 text-sm font-bold">Block name<input name="blocks[{{ $blockIndex }}][name]" value="{{ $block['name'] }}" required class="mt-1 w-full max-w-md rounded-lg border-gray-300"></label><button type="button" onclick="this.closest('section').querySelectorAll('input[type=checkbox]').forEach(item=>item.checked=true)" class="text-sm font-bold text-indigo-700">Select all</button></div>
                    <div class="overflow-x-auto"><table class="w-full min-w-[850px] text-sm"><thead class="text-left text-xs uppercase text-gray-400"><tr><th class="p-4">Import</th><th>Plot number</th><th>Detected dimensions</th><th>Size (marla)</th><th>Confidence</th><th class="pe-4">Note</th></tr></thead><tbody class="divide-y">
                    @foreach($block['plots'] as $plotIndex=>$plot)<tr class="{{ $plot['confidence'] < .7 ? 'bg-amber-50' : '' }}"><td class="p-4"><input type="hidden" name="blocks[{{ $blockIndex }}][plots][{{ $plotIndex }}][include]" value="0"><input type="checkbox" name="blocks[{{ $blockIndex }}][plots][{{ $plotIndex }}][include]" value="1" @checked($plot['confidence'] >= .7) class="rounded border-gray-300 text-indigo-600"></td><td><input name="blocks[{{ $blockIndex }}][plots][{{ $plotIndex }}][plot_number]" value="{{ $plot['plot_number'] }}" required class="w-28 rounded-lg border-gray-300 font-mono font-bold"></td><td class="text-gray-600">{{ $plot['dimensions'] ?: 'Not readable' }}</td><td><input type="number" name="blocks[{{ $blockIndex }}][plots][{{ $plotIndex }}][size_marla]" value="{{ number_format($plot['size_marla'],2,'.','') }}" min="0.01" step="0.01" required class="w-28 rounded-lg border-gray-300"></td><td><span class="rounded-full px-2 py-1 text-xs font-bold {{ $plot['confidence'] >= .85 ? 'bg-green-100 text-green-700' : ($plot['confidence'] >= .7 ? 'bg-blue-100 text-blue-700' : 'bg-amber-100 text-amber-800') }}">{{ number_format($plot['confidence']*100) }}%</span></td><td class="max-w-xs pe-4 text-xs text-gray-500">{{ $plot['note'] ?: '—' }}</td></tr>@endforeach
                    </tbody></table></div>
                </section>
            @endforeach
            <div class="sticky bottom-4 flex items-center justify-between gap-4 rounded-xl border border-indigo-200 bg-white/95 p-4 shadow-xl backdrop-blur"><a href="{{ route('projects.plot-plan.create',$project) }}" class="text-sm font-bold text-gray-600">Discard and upload again</a><button onclick="return confirm('Create the selected plots in inventory?')" class="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white hover:bg-emerald-700">Confirm and create inventory</button></div>
        </form>
    </div></div>
</x-app-layout>
