<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold text-gray-800">Edit booking {{ $booking->booking_number }}</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-3xl px-4">
        @if($errors->any())<div class="mb-5 rounded-lg bg-red-100 p-4 text-red-800"><ul class="list-disc ms-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="mb-5 grid gap-3 rounded-xl bg-white p-5 shadow sm:grid-cols-3"><div><span class="text-xs text-gray-500">Project</span><div class="font-semibold">{{ $booking->project->name }}</div></div><div><span class="text-xs text-gray-500">Package</span><div class="font-semibold">{{ $booking->package->name }}</div></div><div><span class="text-xs text-gray-500">Total price</span><div class="font-semibold">Rs {{ number_format($booking->total_price) }}</div></div></div>
        <form method="POST" action="{{ route('bookings.update',$booking) }}" class="rounded-xl bg-white p-6 shadow space-y-5">@csrf @method('PUT')
            <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Customer name<input name="name" value="{{ old('name',$booking->customer->name) }}" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium">Father name<input name="father_name" value="{{ old('father_name',$booking->customer->father_name) }}" class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium">CNIC<input name="cnic" value="{{ old('cnic',$booking->customer->cnic) }}" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium">Phone<input name="phone" value="{{ old('phone',$booking->customer->phone) }}" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium">Email<input type="email" name="email" value="{{ old('email',$booking->customer->email) }}" class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium">Booking date<input type="date" name="booking_date" value="{{ old('booking_date',$booking->booking_date->toDateString()) }}" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium">Referring customer<select name="agent_id" class="mt-1 w-full rounded-md border-gray-300"><option value="">Direct sale</option>@foreach($agents as $agent)<option value="{{ $agent->id }}" @selected(old('agent_id',$booking->agent_id)==$agent->id)>{{ $agent->name }} — {{ $agent->referral_code }}</option>@endforeach</select></label><label class="text-sm font-medium">Status<select name="status" class="mt-1 w-full rounded-md border-gray-300">@foreach(['pending','approved','active','completed','cancelled','defaulted'] as $status)<option value="{{ $status }}" @selected(old('status',$booking->status)===$status)>{{ $status==='pending'?'Pending approval':($status==='approved'?'Approved — awaiting first payment':ucfirst($status)) }}</option>@endforeach</select></label></div>
            <label class="block text-sm font-medium">Address<textarea name="address" class="mt-1 w-full rounded-md border-gray-300">{{ old('address',$booking->customer->address) }}</textarea></label>
            <p class="rounded-lg bg-amber-50 p-3 text-xs text-amber-800">Cancelling returns this package's land to project inventory. A booking with installment payments cannot be cancelled. Package and project cannot be changed after booking.</p>
            <div class="flex gap-3"><button class="rounded-md bg-indigo-600 px-5 py-2.5 font-semibold text-white">Save booking</button><a href="{{ route('bookings.show',$booking) }}" class="rounded-md border px-5 py-2.5">Cancel</a></div>
        </form>
    </div></div>
</x-app-layout>
