<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h2 class="font-semibold text-xl text-gray-800">{{ $project->name }} — New Booking</h2><form method="GET" action="{{ route('sales.create') }}"><select name="project" onchange="this.form.submit()" class="rounded-md border-gray-300 text-sm">@foreach($projects as $item)<option value="{{ $item->id }}" @selected($item->is($project))>{{ $item->name }}</option>@endforeach</select></form></div></x-slot>
    <div class="py-8"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        @if(session('success'))<div class="rounded-lg bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-lg bg-red-100 p-4 text-red-800"><ul class="list-disc ms-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        <div class="grid gap-4 md:grid-cols-4">
            <div class="rounded-xl bg-white p-5 shadow"><div class="text-sm text-gray-500">Location</div><div class="text-xl font-bold">{{ $project->location }}</div></div>
            <div class="rounded-xl bg-white p-5 shadow"><div class="text-sm text-gray-500">Total area</div><div class="text-xl font-bold">{{ number_format($project->gross_area_marla / 20, 2) }} kanal</div></div>
            <div class="rounded-xl bg-white p-5 shadow"><div class="text-sm text-gray-500">Sold area</div><div class="text-xl font-bold text-amber-600">{{ number_format($project->sold_area_marla / 20, 2) }} kanal</div></div>
            <div class="rounded-xl bg-white p-5 shadow"><div class="text-sm text-gray-500">Available area</div><div class="text-xl font-bold text-green-700">{{ number_format($project->available_area_marla / 20, 2) }} kanal</div></div>
        </div>

        <div class="rounded-xl bg-white p-6 shadow">
            <h3 class="text-lg font-bold mb-4">Packages</h3>
            <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">@foreach($project->packages as $package) @php($availableUnits=(int)floor($project->available_area_marla/$package->size_marla))
                <div class="rounded-lg border p-4 {{ $availableUnits ? '' : 'bg-red-50 opacity-70' }}"><div class="font-bold">{{ $package->name }}</div><div class="text-sm text-gray-500">{{ $package->size_marla }} marla</div><div class="mt-2 text-sm">Total: Rs {{ number_format($package->total_price) }}</div><div class="mt-2 text-xs font-semibold {{ $availableUnits?'text-green-700':'text-red-700' }}">{{ $availableUnits ? number_format($availableUnits).' possible from remaining area' : 'Unavailable' }}</div></div>
            @endforeach</div>
            <p class="mt-4 text-sm text-gray-500">Select a package below to see its exact payment plan.</p>
        </div>

        <div class="grid gap-6 lg:grid-cols-5">
            <form method="POST" action="{{ route('bookings.store') }}" x-data="{ mode: @js(old('customer_id') ? 'existing' : 'new'), packageId: @js((string)old('package_id','')), customerId: @js((string)old('customer_id','')), agentId: @js((string)old('agent_id','')), customerAgents: @js($customers->mapWithKeys(fn($c)=>[(string)$c->id=>(string)$c->referral_agent_id])), packages: @js($project->packages->mapWithKeys(fn($p)=>[(string)$p->id=>['name'=>$p->name,'size'=>(float)$p->size_marla,'booking'=>(float)$p->booking_amount,'monthly'=>(float)$p->monthly_amount,'months'=>(int)$p->months,'balloons'=>$p->balloonPayments(),'total'=>$p->total_price]])) }" x-init="if (mode === 'existing' && customerId) agentId = customerAgents[customerId] || ''" class="lg:col-span-2 rounded-xl bg-white p-6 shadow space-y-4">@csrf
                <h3 class="text-lg font-bold">New booking</h3>
                <label class="block text-sm font-medium">Package<select name="package_id" x-model="packageId" required class="mt-1 w-full rounded-md border-gray-300"><option value="">Select package</option>@foreach($project->packages as $p)<option value="{{ $p->id }}" @disabled($project->available_area_marla < $p->size_marla)>{{ $p->name }} ({{ $p->size_marla }} marla)</option>@endforeach</select></label>
                <div x-show="packageId && packages[packageId]" x-cloak class="rounded-lg bg-indigo-50 p-4 text-sm"><div class="mb-2 font-bold text-indigo-900" x-text="packages[packageId]?.name + ' payment plan'"></div><div class="grid grid-cols-2 gap-2 text-indigo-800"><span>First payment</span><b class="text-right" x-text="'Rs '+packages[packageId]?.booking.toLocaleString()"></b><span x-text="packages[packageId]?.months + ' monthly payments'"></span><b class="text-right" x-text="'Rs '+packages[packageId]?.monthly.toLocaleString()+' each'"></b><template x-for="balloon in packages[packageId]?.balloons || []" :key="balloon.month"><span class="contents"><span x-text="'Month '+balloon.month+' balloon'"></span><b class="text-right" x-text="'Rs '+Number(balloon.amount).toLocaleString()"></b></span></template><span class="border-t pt-2">Total price</span><b class="border-t pt-2 text-right" x-text="'Rs '+packages[packageId]?.total.toLocaleString()"></b></div></div>
                <div class="grid grid-cols-2 rounded-lg bg-gray-100 p-1 text-sm"><button type="button" @click="mode='new'" :class="mode==='new'?'bg-white shadow text-indigo-700':''" class="rounded-md px-3 py-2 font-semibold">New customer</button><button type="button" @click="mode='existing'" :class="mode==='existing'?'bg-white shadow text-indigo-700':''" class="rounded-md px-3 py-2 font-semibold">Existing customer</button></div>
                <div x-show="mode==='existing'" x-cloak><label class="block text-sm font-medium">Select customer<select name="customer_id" x-model="customerId" @change="agentId=customerAgents[customerId] || ''" :disabled="mode!=='existing'" :required="mode==='existing'" class="mt-1 w-full rounded-md border-gray-300"><option value="">Choose customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }} — {{ $customer->referral_code }} — {{ $customer->phone }}</option>@endforeach</select></label><div x-show="customerId" class="mt-2 rounded bg-green-50 p-2 text-xs font-medium text-green-700">The customer's assigned sales agent is selected automatically.</div><a href="{{ route('customers.create') }}" class="mt-2 inline-block text-xs text-indigo-600">Customer not listed? Add customer first</a></div>
                <div x-show="mode==='new'" class="space-y-4"><div class="grid grid-cols-2 gap-3"><label class="text-sm">Customer name<input name="name" value="{{ old('name') }}" :required="mode==='new'" :disabled="mode!=='new'" class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm">Father name<input name="father_name" value="{{ old('father_name') }}" :disabled="mode!=='new'" class="mt-1 w-full rounded-md border-gray-300"></label></div><div class="grid grid-cols-2 gap-3"><label class="text-sm">CNIC<input name="cnic" value="{{ old('cnic') }}" :required="mode==='new'" :disabled="mode!=='new'" class="mt-1 w-full rounded-md border-gray-300" placeholder="00000-0000000-0"></label><label class="text-sm">Phone<input name="phone" value="{{ old('phone') }}" :required="mode==='new'" :disabled="mode!=='new'" class="mt-1 w-full rounded-md border-gray-300"></label></div><label class="block text-sm">Email<input type="email" name="email" value="{{ old('email') }}" :disabled="mode!=='new'" class="mt-1 w-full rounded-md border-gray-300"></label><label class="block text-sm">Address<textarea name="address" :disabled="mode!=='new'" class="mt-1 w-full rounded-md border-gray-300">{{ old('address') }}</textarea></label></div>
                <label class="block text-sm">Sales agent<select name="agent_id" x-model="agentId" :disabled="mode==='existing' && customerId" class="mt-1 w-full rounded-md border-gray-300 disabled:cursor-not-allowed disabled:bg-gray-100"><option value="">Direct sale</option>@foreach($agents as $agent)<option value="{{ $agent->id }}">{{ $agent->name }}</option>@endforeach</select><span x-show="mode==='existing' && customerId" class="mt-1 block text-xs text-gray-500">Assigned from the selected customer.</span></label>
                <div class="grid grid-cols-2 gap-3"><label class="text-sm">Booking date<input type="date" name="booking_date" value="{{ old('booking_date', now()->toDateString()) }}" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm">Payment method<select name="payment_method" class="mt-1 w-full rounded-md border-gray-300"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="cheque">Cheque</option><option value="card">Card</option></select></label></div>
                <label class="block text-sm">Transaction reference<input name="transaction_reference" class="mt-1 w-full rounded-md border-gray-300"></label>
                <button :disabled="!packageId" class="w-full rounded-md bg-indigo-600 px-4 py-3 font-semibold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:bg-gray-400"><span x-text="packageId && packages[packageId] ? 'Confirm booking & receive Rs '+packages[packageId].booking.toLocaleString() : 'Select a package to continue'"></span></button>
            </form>
            <div class="lg:col-span-3 rounded-xl bg-white p-6 shadow overflow-x-auto">
                <h3 class="text-lg font-bold mb-4">Recent bookings</h3>
                <table class="w-full text-sm"><thead><tr class="border-b text-left text-gray-500"><th class="py-2">Booking</th><th>Customer</th><th>Package</th><th>Agent #</th><th>Status</th><th></th></tr></thead><tbody>@forelse($bookings as $booking)<tr class="border-b"><td class="py-3 font-medium">{{ $booking->booking_number }}</td><td>{{ $booking->customer->name }}</td><td>{{ $booking->package->name }}</td><td>{{ $booking->agent?->referral_code ?? 'Direct' }}</td><td><span class="rounded-full bg-green-100 px-2 py-1 text-green-700">{{ ucfirst($booking->status) }}</span></td><td><a class="text-indigo-600" href="{{ route('bookings.show',$booking) }}">View</a></td></tr>@empty<tr><td colspan="6" class="py-8 text-center text-gray-500">No bookings yet.</td></tr>@endforelse</tbody></table>
            </div>
        </div>
    </div></div>
</x-app-layout>
