<x-app-layout>
<div class="py-8"><div class="mx-auto max-w-5xl space-y-6 px-4">@if($errors->any())<div class="rounded-xl bg-red-100 p-4 text-red-800">{{ $errors->first() }}</div>@endif
<section class="overflow-hidden rounded-2xl bg-gradient-to-r from-slate-950 via-indigo-950 to-violet-900 text-white shadow-xl"><div class="flex flex-col gap-3 border-b border-white/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div class="text-[10px] font-black uppercase tracking-[.18em] text-indigo-300">Manage booking</div><h2 class="mt-1 font-mono text-xl font-black">{{ $booking->booking_number }}</h2></div><a href="{{ route('bookings.index') }}" class="inline-flex w-fit items-center rounded-xl border border-white/15 bg-white/10 px-4 py-2.5 text-sm font-black text-white transition hover:bg-white hover:text-indigo-900">← Bookings</a></div><div class="grid gap-5 p-6 sm:grid-cols-4"><div><small class="text-indigo-300">CUSTOMER</small><b class="block">{{ $booking->customer->name }}</b><span class="text-xs text-slate-300">{{ $booking->customer->referral_code }}</span></div><div><small class="text-indigo-300">PROJECT / PACKAGE</small><b class="block">{{ $booking->project->name }}</b><span class="text-xs text-slate-300">{{ $booking->package->name }}</span></div><div><small class="text-indigo-300">TOTAL</small><b class="block">Rs {{ number_format($booking->total_price,2) }}</b></div><div><small class="text-indigo-300">STATUS</small><b class="block">{{ ucfirst($booking->status) }}</b></div></div></section>
<form method="POST" action="{{ route('bookings.status',$booking) }}" x-data="{decision:@js(old('status','')),notes:@js(old('management_notes', $booking->management_notes ?? '')),addNote(note){const current=(this.notes||'').trim();this.notes=current?current+'\n'+note:note}}" @submit="if(!confirm('Apply this booking decision?')) $event.preventDefault()" class="rounded-2xl bg-white p-6 shadow-xl">@csrf @method('PATCH')<h3 class="text-lg font-black">Booking decision</h3><p class="text-sm text-slate-500">Choose an action and add management notes.</p>
<div class="mt-5 grid gap-3 sm:grid-cols-2">@if($booking->status==='pending')
<label><input class="peer sr-only" type="radio" name="status" value="approved" x-model="decision"><div class="cursor-pointer rounded-xl border-2 p-4 peer-checked:border-emerald-500 peer-checked:bg-emerald-50"><b class="text-emerald-700">✓ Approve request</b><p class="mt-1 text-xs text-slate-500">Allow the customer to submit the first payment.</p></div></label>
<label><input class="peer sr-only" type="radio" name="status" value="cancelled" x-model="decision"><div class="cursor-pointer rounded-xl border-2 p-4 peer-checked:border-red-500 peer-checked:bg-red-50"><b class="text-red-700">✕ Reject request</b><p class="mt-1 text-xs text-slate-500">Reject and release reserved inventory.</p></div></label>
@elseif(in_array($booking->status,['approved','active','defaulted']))<label><input class="peer sr-only" type="radio" name="status" value="cancelled" x-model="decision"><div class="cursor-pointer rounded-xl border-2 p-4 peer-checked:border-red-500 peer-checked:bg-red-50"><b class="text-red-700">Cancel booking</b></div></label>@if($booking->status==='active')<label><input class="peer sr-only" type="radio" name="status" value="defaulted" x-model="decision"><div class="cursor-pointer rounded-xl border-2 p-4 peer-checked:border-amber-500 peer-checked:bg-amber-50"><b class="text-amber-700">Mark defaulted</b></div></label>@endif @else<div class="rounded-xl bg-slate-50 p-5 text-slate-500">No actions available.</div>@endif</div>
<div class="mt-5"><div class="mb-2 flex items-center justify-between"><span class="text-xs font-black uppercase tracking-wide text-slate-500">Quick notes</span><button type="button" @click="notes=''" class="text-xs font-bold text-slate-400 hover:text-red-600">Clear</button></div><div class="flex flex-wrap gap-2">@foreach(['Customer details and selected package have been reviewed.','Booking documents have been verified.','Customer was contacted and the booking decision was explained.','Request requires additional information before processing.'] as $note)<button type="button" @click="addNote(@js($note))" class="rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-left text-xs font-semibold text-indigo-700 hover:bg-indigo-600 hover:text-white">+ {{ $note }}</button>@endforeach</div></div>
<label class="mt-4 block text-sm font-semibold">Management notes <span x-show="decision==='cancelled'||decision==='defaulted'" class="text-red-600">(required)</span><textarea name="management_notes" x-model="notes" rows="4" class="mt-1 w-full rounded-xl border-slate-300"></textarea></label><div class="mt-5 flex justify-end gap-3"><a href="{{ route('bookings.show',$booking) }}" class="rounded-lg border px-5 py-2.5 font-semibold">View booking</a><button :disabled="!decision" class="rounded-lg bg-indigo-600 px-6 py-2.5 font-black text-white disabled:bg-slate-300">Save decision</button></div></form>
</div></div></x-app-layout>
