<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <h2 class="break-all text-lg font-semibold dark:text-white sm:text-xl">Booking {{ $booking->booking_number }}</h2>
        <div class="grid grid-cols-2 gap-3 sm:flex"><a href="{{ route('bookings.edit',$booking) }}" class="rounded-lg bg-amber-50 px-4 py-2 text-center font-bold text-amber-700">Edit</a><a href="{{ route('bookings.index') }}" class="rounded-lg border px-4 py-2 text-center font-bold text-indigo-600 dark:border-slate-600 dark:text-indigo-300">← Bookings</a></div></div></x-slot>
    <div class="py-5 sm:py-8"><div class="max-w-7xl mx-auto px-3 sm:px-4 space-y-6">
        @if(session('success'))<div class="rounded-lg bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-lg bg-red-100 p-4 text-red-800">{{ $errors->first() }}</div>@endif

        <div class="grid gap-4 md:grid-cols-4"><div class="bg-white rounded-xl p-5 shadow"><span class="text-gray-500 text-sm">Customer</span><div class="font-bold">{{ $booking->customer->name }}</div></div><div class="bg-white rounded-xl p-5 shadow"><span class="text-gray-500 text-sm">Package</span><div class="font-bold">{{ $booking->package->name }}</div><div class="mt-1 text-xs font-bold text-violet-600">{{ $booking->payment_plan === 'cash' ? 'Cash plan' : 'Installment plan' }}</div></div><div class="bg-white rounded-xl p-5 shadow"><span class="text-gray-500 text-sm">{{ $booking->payment_plan === 'cash' ? 'Cash price' : 'Installment price' }}</span><div class="font-bold">Rs {{ number_format($booking->total_price) }}</div></div><div class="bg-white rounded-xl p-5 shadow"><span class="text-gray-500 text-sm">Referrer</span>@if($booking->agent)<a href="{{ route('customers.show',$booking->agent) }}" class="block font-bold text-indigo-600">{{ $booking->agent->name }}</a><div class="text-xs font-semibold text-gray-500">Referral # {{ $booking->agent->referral_code }}</div>@else<div class="font-bold">Direct sale</div>@endif</div></div>
        <div class="grid gap-6 lg:grid-cols-4"><form method="POST" action="{{ route('bookings.payments.store',$booking) }}" class="bg-white rounded-xl p-5 shadow space-y-3">@csrf<h3 class="font-bold">Record installment</h3><label class="block text-sm">Month<select name="installment_number" class="mt-1 w-full rounded-md border-gray-300">@foreach($booking->installments->where('status','!=','paid') as $i)<option value="{{ $i->installment_number }}">Month {{ $i->installment_number }} — Rs {{ number_format($i->total_due-$i->paid_amount) }}</option>@endforeach</select></label><label class="block text-sm">Amount<input type="number" name="amount" min="1" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="block text-sm">Method<select name="payment_method" class="mt-1 w-full rounded-md border-gray-300"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="cheque">Cheque</option></select></label><input name="transaction_reference" placeholder="Reference (optional)" class="w-full rounded-md border-gray-300"><button class="w-full rounded bg-indigo-600 p-2 text-white">Record payment</button></form>
        <div class="lg:col-span-3 bg-white rounded-xl p-3 shadow sm:p-5 dark:bg-slate-800 dark:text-white"><h3 class="font-bold mb-3 px-1">36-month schedule</h3><table class="admin-booking-schedule w-full text-sm"><thead><tr class="border-b text-left dark:border-slate-700"><th>Month</th><th>Due date</th><th>Regular</th><th>Balloon</th><th>Total</th><th>Paid</th><th>Status</th></tr></thead><tbody>@foreach($booking->installments as $i)<tr class="border-b dark:border-slate-700"><td data-label="Month" class="py-2">{{ $i->installment_number }}</td><td data-label="Due date">{{ $i->due_date->format('d M Y') }}</td><td data-label="Regular">Rs {{ number_format($i->regular_amount) }}</td><td data-label="Balloon">Rs {{ number_format($i->balloon_amount) }}</td><td data-label="Total" class="font-medium">Rs {{ number_format($i->total_due) }}</td><td data-label="Paid">Rs {{ number_format($i->paid_amount) }}</td><td data-label="Status">{{ ucfirst($i->status) }}</td></tr>@endforeach</tbody></table></div></div>
    </div></div>
</x-app-layout>
