<x-app-layout>
    <x-slot name="header"><div class="flex justify-between">
        <h2 class="font-semibold text-xl">Booking {{ $booking->booking_number }}</h2>
        <div class="flex gap-4"><a href="{{ route('bookings.edit',$booking) }}" class="text-amber-700">Edit</a><a href="{{ route('bookings.index') }}" class="text-indigo-600">← Bookings</a></div></div></x-slot>
    <div class="py-8"><div class="max-w-7xl mx-auto px-4 space-y-6">
        @if(session('success'))<div class="rounded-lg bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-lg bg-red-100 p-4 text-red-800">{{ $errors->first() }}</div>@endif

        <div class="grid gap-4 md:grid-cols-4"><div class="bg-white rounded-xl p-5 shadow"><span class="text-gray-500 text-sm">Customer</span><div class="font-bold">{{ $booking->customer->name }}</div></div><div class="bg-white rounded-xl p-5 shadow"><span class="text-gray-500 text-sm">Package</span><div class="font-bold">{{ $booking->package->name }}</div><div class="mt-1 text-xs font-bold text-violet-600">{{ $booking->payment_plan === 'cash' ? 'Cash plan' : 'Installment plan' }}</div></div><div class="bg-white rounded-xl p-5 shadow"><span class="text-gray-500 text-sm">{{ $booking->payment_plan === 'cash' ? 'Cash price' : 'Installment price' }}</span><div class="font-bold">Rs {{ number_format($booking->total_price) }}</div></div><div class="bg-white rounded-xl p-5 shadow"><span class="text-gray-500 text-sm">Referrer</span>@if($booking->agent)<a href="{{ route('customers.show',$booking->agent) }}" class="block font-bold text-indigo-600">{{ $booking->agent->name }}</a><div class="text-xs font-semibold text-gray-500">Referral # {{ $booking->agent->referral_code }}</div>@else<div class="font-bold">Direct sale</div>@endif</div></div>
        <div class="grid gap-6 lg:grid-cols-4"><form method="POST" action="{{ route('bookings.payments.store',$booking) }}" class="bg-white rounded-xl p-5 shadow space-y-3">@csrf<h3 class="font-bold">Record installment</h3><label class="block text-sm">Month<select name="installment_number" class="mt-1 w-full rounded-md border-gray-300">@foreach($booking->installments->where('status','!=','paid') as $i)<option value="{{ $i->installment_number }}">Month {{ $i->installment_number }} — Rs {{ number_format($i->total_due-$i->paid_amount) }}</option>@endforeach</select></label><label class="block text-sm">Amount<input type="number" name="amount" min="1" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="block text-sm">Method<select name="payment_method" class="mt-1 w-full rounded-md border-gray-300"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="cheque">Cheque</option></select></label><input name="transaction_reference" placeholder="Reference (optional)" class="w-full rounded-md border-gray-300"><button class="w-full rounded bg-indigo-600 p-2 text-white">Record payment</button></form>
        <div class="lg:col-span-3 bg-white rounded-xl p-5 shadow overflow-x-auto"><h3 class="font-bold mb-3">36-month schedule</h3><table class="w-full text-sm"><thead><tr class="border-b text-left"><th>Month</th><th>Due date</th><th>Regular</th><th>Balloon</th><th>Total</th><th>Paid</th><th>Status</th></tr></thead><tbody>@foreach($booking->installments as $i)<tr class="border-b"><td class="py-2">{{ $i->installment_number }}</td><td>{{ $i->due_date->format('d M Y') }}</td><td>Rs {{ number_format($i->regular_amount) }}</td><td>Rs {{ number_format($i->balloon_amount) }}</td><td class="font-medium">Rs {{ number_format($i->total_due) }}</td><td>Rs {{ number_format($i->paid_amount) }}</td><td>{{ ucfirst($i->status) }}</td></tr>@endforeach</tbody></table></div></div>
    </div></div>
</x-app-layout>
