<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold text-gray-800 dark:text-white">Edit installment {{ $installment->installment_number }}</h2></x-slot>
    <div class="py-5 sm:py-8"><div class="mx-auto max-w-2xl px-3 sm:px-4">
        @if($errors->any())<div class="mb-5 rounded-lg bg-red-100 p-4 text-red-800"><ul class="list-disc ms-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="mb-5 rounded-xl bg-white p-4 shadow dark:bg-slate-800 dark:text-white sm:p-5"><div class="grid gap-3 text-sm sm:grid-cols-2"><div><span class="text-gray-500 dark:text-slate-400">Booking</span><div class="break-all font-semibold">{{ $installment->booking->booking_number }}</div></div><div><span class="text-gray-500 dark:text-slate-400">Customer</span><div class="font-semibold">{{ $installment->booking->customer->name }}</div></div><div><span class="text-gray-500 dark:text-slate-400">Package</span><div class="font-semibold">{{ $installment->booking->package->name }}</div></div><div><span class="text-gray-500 dark:text-slate-400">Already paid</span><div class="font-semibold">Rs {{ number_format($installment->paid_amount) }}</div></div></div></div>
        <form method="POST" action="{{ route('installments.update',$installment) }}" class="rounded-xl bg-white p-4 shadow space-y-5 dark:bg-slate-800 dark:text-white sm:p-6">@csrf @method('PUT')
            <label class="block text-sm font-medium">Due date<input type="date" name="due_date" value="{{ old('due_date',$installment->due_date->toDateString()) }}" required class="mt-1 w-full rounded-md border-gray-300"></label>
            <div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-medium">Regular amount<input type="number" step="0.01" min="0" name="regular_amount" value="{{ old('regular_amount',$installment->regular_amount) }}" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="block text-sm font-medium">Balloon amount<input type="number" step="0.01" min="0" name="balloon_amount" value="{{ old('balloon_amount',$installment->balloon_amount) }}" required class="mt-1 w-full rounded-md border-gray-300"></label></div>
            <label class="block text-sm font-medium">Administrative status<select name="status" class="mt-1 w-full rounded-md border-gray-300"><option value="pending" @selected(old('status',$installment->status)==='pending')>Active / pending</option><option value="waived" @selected(old('status',$installment->status)==='waived')>Waived</option><option value="cancelled" @selected(old('status',$installment->status)==='cancelled')>Cancelled</option></select></label>
            <p class="text-xs text-gray-500">Paid and partial statuses are calculated automatically. An installment with a payment cannot be waived or cancelled.</p>
            <div class="grid grid-cols-2 gap-3"><button class="rounded-md bg-indigo-600 px-3 py-2.5 font-semibold text-white">Save installment</button><a href="{{ route('installments.index',['booking'=>$installment->booking_id]) }}" class="rounded-md border px-3 py-2.5 text-center dark:border-slate-600">Cancel</a></div>
        </form>
    </div></div>
</x-app-layout>
