<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold text-gray-800">Manage installments</h2></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl px-4 space-y-5">
        @if(session('success'))<div class="rounded-lg bg-green-100 p-4 text-green-800">{{ session('success') }}</div>@endif
        <form method="GET" class="grid gap-4 rounded-xl bg-white p-5 shadow sm:grid-cols-4">
            <label class="text-sm font-medium">Project<select name="project" class="mt-1 w-full rounded-md border-gray-300"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected(request('project')==$project->id)>{{ $project->name }}</option>@endforeach</select></label>
            <label class="text-sm font-medium">Booking<select name="booking" data-booking-filter-select class="mt-1 w-full rounded-md border-gray-300"><option value="">All bookings</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}" @selected(request('booking')==$booking->id)>{{ $booking->booking_number }} — {{ $booking->customer->name }}</option>@endforeach</select></label>
            <label class="text-sm font-medium">Status<select name="status" class="mt-1 w-full rounded-md border-gray-300"><option value="">Next upcoming per customer</option>@foreach(['upcoming','pending','partial','paid','overdue','waived','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label>
            <div class="flex items-end gap-2"><button class="rounded-md bg-indigo-600 px-5 py-2.5 font-semibold text-white">Filter</button><a href="{{ route('installments.index') }}" class="rounded-md border px-4 py-2.5">Clear</a></div>
        </form>
        <div class="overflow-x-auto rounded-xl bg-white shadow"><table class="w-full text-sm"><thead class="bg-gray-50 text-left text-gray-500"><tr><th class="p-4">Booking / Customer</th><th>Project</th><th>Month</th><th>Due date</th><th>Regular</th><th>Balloon</th><th>Total</th><th>Paid</th><th>Status</th><th></th></tr></thead><tbody>
        @forelse($installments as $installment) @php($displayStatus = in_array($installment->status,['pending','partial']) && $installment->due_date->lt(today()) ? 'overdue' : ($nextUpcomingIds->contains($installment->id) ? 'upcoming' : $installment->status))
        <tr class="border-t"><td class="p-4"><a href="{{ route('bookings.show',$installment->booking) }}" class="font-semibold text-indigo-600">{{ $installment->booking->booking_number }}</a><div class="text-xs text-gray-500">{{ $installment->booking->customer->name }}</div></td><td>{{ $installment->booking->project->name }}</td><td>{{ $installment->installment_number }}</td><td>{{ $installment->due_date->format('d M Y') }}</td><td>Rs {{ number_format($installment->regular_amount) }}</td><td>Rs {{ number_format($installment->balloon_amount) }}</td><td class="font-semibold">Rs {{ number_format($installment->total_due) }}</td><td>Rs {{ number_format($installment->paid_amount) }}</td><td><span class="rounded-full px-2 py-1 {{ $displayStatus==='paid'?'bg-green-100 text-green-700':($displayStatus==='overdue'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700') }}">{{ ucfirst($displayStatus) }}</span></td><td class="pe-4"><a href="{{ route('installments.edit',$installment) }}" class="text-indigo-600">Edit</a></td></tr>
        @empty<tr><td colspan="10" class="p-10 text-center text-gray-500">No installments found.</td></tr>@endforelse</tbody></table></div>
        {{ $installments->links() }}
    </div></div>
</x-app-layout>
