<x-app-layout>
    <div class="relative min-h-screen overflow-hidden bg-gradient-to-br from-indigo-50 via-white to-emerald-50 py-6 dark:from-slate-950 dark:via-slate-950 dark:to-emerald-950/30 sm:py-8">
        <div class="pointer-events-none absolute -left-32 top-24 h-96 w-96 rounded-full bg-violet-200/40 blur-3xl dark:bg-violet-900/20"></div>
        <div class="pointer-events-none absolute -right-32 top-[34rem] h-96 w-96 rounded-full bg-emerald-200/40 blur-3xl dark:bg-emerald-900/20"></div>
        <div class="relative w-full space-y-6 px-3 sm:px-5 lg:px-6">
            <section class="relative isolate overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-emerald-900 to-teal-600 p-6 text-white shadow-2xl shadow-emerald-200/70 dark:shadow-none sm:p-8">
                <div class="absolute -right-16 -top-20 -z-10 h-72 w-72 rounded-full bg-cyan-300/25 blur-3xl"></div>
                <div class="absolute inset-0 -z-10 opacity-[.07]" style="background-image:radial-gradient(circle at 1px 1px,#fff 1px,transparent 0);background-size:22px 22px"></div>
                <div class="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end">
                    <div><span class="inline-flex rounded-full border border-emerald-200/20 bg-white/10 px-3 py-1 text-[10px] font-black uppercase tracking-[.18em] text-emerald-100">Commission wallet</span><h1 class="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Withdraw your earnings</h1><p class="mt-2 max-w-xl text-sm leading-6 text-emerald-100">Submit a secure withdrawal request using your preferred payout account. The office will review it before payment.</p></div>
                    <div class="rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur"><div class="text-[10px] font-black uppercase tracking-wider text-emerald-200">Available to request</div><div class="mt-1 text-3xl font-black">Rs {{ number_format($available, 2) }}</div></div>
                </div>
            </section>

            @if(session('success'))<div class="flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800 shadow-sm"><span class="grid h-7 w-7 place-items-center rounded-full bg-emerald-500 text-white">✓</span>{{ session('success') }}</div>@endif
            @if(session('error'))<div class="flex items-center gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-800 shadow-sm"><span class="grid h-7 w-7 place-items-center rounded-full bg-rose-500 text-white">!</span>{{ session('error') }}</div>@endif
            @if($errors->any())<div class="flex items-start gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-800 shadow-sm"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-rose-500 text-white">!</span>{{ $errors->first() }}</div>@endif

            <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                <div class="rounded-3xl bg-gradient-to-br from-emerald-500 to-teal-700 p-5 text-white shadow-xl shadow-emerald-200/60"><div class="text-[10px] font-black uppercase tracking-wider text-emerald-100">Payable commission</div><div class="mt-3 text-2xl font-black">Rs {{ number_format($payable, 2) }}</div><p class="mt-1 text-xs text-emerald-100">Earned commission awaiting payout</p></div>
                <div class="rounded-3xl bg-gradient-to-br from-amber-400 to-orange-600 p-5 text-white shadow-xl shadow-amber-200/60"><div class="text-[10px] font-black uppercase tracking-wider text-amber-50">Pending requests</div><div class="mt-3 text-2xl font-black">Rs {{ number_format($pending, 2) }}</div><p class="mt-1 text-xs text-amber-50">Reserved while under review</p></div>
                <div class="rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-700 p-5 text-white shadow-xl shadow-indigo-200/60"><div class="text-[10px] font-black uppercase tracking-wider text-indigo-100">Approved withdrawals</div><div class="mt-3 text-2xl font-black">Rs {{ number_format($withdrawn, 2) }}</div><p class="mt-1 text-xs text-indigo-100">Total approved requests</p></div>
                <div class="rounded-3xl bg-gradient-to-br from-fuchsia-600 to-rose-600 p-5 text-white shadow-xl shadow-fuchsia-200/60"><div class="text-[10px] font-black uppercase tracking-wider text-fuchsia-100">Lifetime earnings</div><div class="mt-3 text-2xl font-black">Rs {{ number_format($lifetime, 2) }}</div><p class="mt-1 text-xs text-fuchsia-100">All commission generated to date</p></div>
            </div>

            <div class="grid items-start gap-5 md:grid-cols-3">
                <section class="overflow-hidden rounded-2xl border border-emerald-100 bg-white shadow-lg shadow-slate-200/60 dark:border-slate-700 dark:bg-slate-900 dark:shadow-none">
                    <div class="border-b border-slate-100 bg-gradient-to-r from-emerald-50 to-white px-4 py-3.5 dark:border-slate-800 dark:from-emerald-950/30 dark:to-slate-900">
                        <h2 class="text-sm font-black text-slate-950 dark:text-white">New withdrawal request</h2>
                        <p class="mt-1 text-xs text-slate-500 dark:text-slate-300">{{ ucfirst($frequency) }} limit: {{ $policy['request_limit'] }} request{{ $policy['request_limit'] === 1 ? '' : 's' }}. {{ $remainingRequests }} remaining this period.</p>
                        <div class="mt-2 flex flex-wrap gap-1.5">
                            <span class="rounded-full bg-emerald-100 px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">{{ ucfirst($frequency) }}</span>
                            <span class="rounded-full bg-indigo-100 px-2.5 py-1 text-[9px] font-black tracking-wider text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">Withdrawal day: {{ ucfirst(str_replace(['every ', 'on any day'], ['', 'Any day'], $withdrawalDayLabel)) }}</span>
                        </div>
                        <p class="mt-1 text-[10px] font-bold {{ $withdrawalDayAllowed ? 'text-emerald-600 dark:text-emerald-300' : 'text-rose-600 dark:text-rose-300' }}">Requests accepted {{ $policy['withdrawal_day'] ? 'before '.ucfirst(str_replace('every ', '', $withdrawalDayLabel)) : 'on any day' }}{{ $withdrawalDayAllowed ? '.' : ' — submissions are closed today.' }}</p>
                    </div>
                    <form method="POST" action="{{ route('customer.withdrawals.store') }}" x-data="{ amount: @js((float) old('amount', $maximumRequestAmount)), feeEnabled: @js($fee['enabled']), feeType: @js($fee['type']), feeValue: @js($fee['value']), feeAmount(){ return !this.feeEnabled ? 0 : Math.round((this.feeType === 'percentage' ? Number(this.amount || 0) * Number(this.feeValue) / 100 : Number(this.feeValue)) * 100) / 100 }, money(value){ return Number(value || 0).toLocaleString('en-PK', {minimumFractionDigits: 2, maximumFractionDigits: 2}) } }" class="space-y-3 p-4">@csrf
                        <label class="block text-[10px] font-black uppercase tracking-wide text-slate-500">Amount (Rs)<div class="relative mt-1"><span class="absolute left-3 top-1/2 -translate-y-1/2 text-sm font-black text-emerald-600">Rs</span><input type="number" name="amount" x-model.number="amount" min="{{ $policy['minimum_amount'] }}" max="{{ $maximumRequestAmount }}" step="0.01" required class="w-full rounded-lg border-emerald-200 bg-emerald-50/50 py-2.5 pl-10 text-base font-black text-slate-950 dark:bg-slate-800 dark:text-white"></div><span class="mt-1 block text-[10px] normal-case text-slate-400">Minimum Rs {{ number_format($policy['minimum_amount'], 2) }}. Maximum {{ $policy['maximum_amount'] > 0 ? 'Rs '.number_format($maximumRequestAmount, 2) : 'your available commission' }}.</span></label>
                        @if($payoutMethods->isNotEmpty())
                            <label class="block text-[10px] font-black uppercase tracking-wide text-slate-500">Saved payout method<select name="payout_method_id" required class="mt-1 w-full rounded-lg border-slate-300 py-2.5 text-xs normal-case dark:border-slate-700 dark:bg-slate-800 dark:text-white">@foreach($payoutMethods as $method)<option value="{{ $method->id }}" @selected((string) old('payout_method_id', $payoutMethods->firstWhere('is_default', true)?->id ?? $payoutMethods->first()->id) === (string) $method->id)>{{ $method->label }} — {{ ucwords(str_replace('_', ' ', $method->payment_method)) }} — {{ $method->account_number }}</option>@endforeach</select></label>
                            <a href="{{ route('customer.payout-methods.index') }}" class="block text-xs font-black text-indigo-600 hover:text-indigo-800">Manage payout methods →</a>
                        @else
                            <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><b class="block">Add a payout method first</b><span class="mt-1 block text-xs">Save a bank account or wallet before requesting a withdrawal.</span><a href="{{ route('customer.payout-methods.index') }}" class="mt-3 inline-flex rounded-lg bg-amber-600 px-3 py-2 text-xs font-black text-white">Add payout method</a></div>
                        @endif
                        <label class="block text-[10px] font-black uppercase tracking-wide text-slate-500">Notes <span class="font-normal normal-case">(optional)</span><textarea name="notes" rows="2" maxlength="500" class="mt-1 w-full rounded-lg border-slate-300 text-xs dark:border-slate-700 dark:bg-slate-800 dark:text-white" placeholder="Bank name or other instructions">{{ old('notes') }}</textarea></label>
                        @if($fee['enabled'])
                            <div class="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs">
                                <div class="mb-2 flex items-center justify-between"><b class="text-amber-900">Withdrawal breakdown</b><span class="rounded-full bg-amber-200 px-2 py-0.5 text-[9px] font-black uppercase text-amber-800">{{ $fee['type'] === 'percentage' ? number_format($fee['value'], 2).'%' : 'Fixed fee' }}</span></div>
                                <dl class="space-y-1.5 text-slate-600"><div class="flex justify-between"><dt>Requested amount</dt><dd class="font-bold">Rs <span x-text="money(amount)"></span></dd></div><div class="flex justify-between text-rose-600"><dt>Withdrawal fee</dt><dd class="font-bold">− Rs <span x-text="money(feeAmount())"></span></dd></div><div class="flex justify-between border-t border-amber-200 pt-2 text-sm font-black text-emerald-700"><dt>You receive</dt><dd>Rs <span x-text="money(Math.max(0, Number(amount || 0) - feeAmount()))"></span></dd></div></dl>
                            </div>
                        @endif
                        @if($pinLockedUntil)
                            <div class="rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-800"><div class="flex items-start gap-2"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-rose-200 text-base">🔒</span><div><b class="block">Withdrawals temporarily locked</b><span class="mt-1 block text-[10px] leading-4">Four incorrect PIN attempts were entered. You can try again after <b>{{ $pinLockedUntil->format('d M Y, h:i A') }}</b>.</span></div></div></div>
                        @elseif(filled(auth()->user()->withdrawal_pin))
                            <label class="block rounded-xl border border-indigo-100 bg-indigo-50/60 p-3 text-[10px] font-black uppercase tracking-wide text-indigo-700 dark:border-indigo-900 dark:bg-indigo-950/30 dark:text-indigo-300">Withdrawal PIN<div class="relative mt-1.5"><input type="password" name="withdrawal_pin" required inputmode="numeric" pattern="[0-9]{4,6}" minlength="4" maxlength="6" autocomplete="off" class="w-full rounded-lg border-indigo-200 bg-white py-2.5 pe-10 font-mono text-base tracking-[.4em] text-slate-950 dark:border-slate-700 dark:bg-slate-800 dark:text-white" placeholder="••••"><span class="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-base">🔒</span></div><span class="mt-1.5 block font-normal normal-case tracking-normal text-indigo-500">Enter the PIN you created in Profile & Security.</span></label>
                        @else
                            <div class="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><b class="block">Withdrawal PIN required</b><span class="mt-1 block text-[10px]">Protect your balance by creating a PIN before submitting a request.</span><a href="{{ route('profile.edit') }}" class="mt-2 inline-flex rounded-lg bg-amber-600 px-3 py-2 text-[10px] font-black text-white">Set withdrawal PIN →</a></div>
                        @endif
                        <x-input-error :messages="$errors->get('withdrawal_pin')" />
                        <button @disabled(! $withdrawalDayAllowed || $pinLockedUntil || blank(auth()->user()->withdrawal_pin) || $payoutMethods->isEmpty() || $remainingRequests < 1 || $maximumRequestAmount < $policy['minimum_amount']) class="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-emerald-600 to-teal-600 px-4 py-2.5 text-xs font-black text-white shadow-md shadow-emerald-200 transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 dark:shadow-none">Submit withdrawal request <span>→</span></button>
                    </form>
                </section>

                <section class="overflow-hidden rounded-3xl border border-indigo-100 bg-white shadow-xl shadow-slate-200/70 dark:border-slate-700 dark:bg-slate-900 dark:shadow-none md:col-span-2">
                    <div class="border-b border-slate-100 p-5 dark:border-slate-800"><h2 class="font-black text-slate-950 dark:text-white">Withdrawal history</h2><p class="mt-1 text-xs text-slate-500 dark:text-slate-300">Track every request and its review status.</p></div>
                    <div class="overflow-x-auto"><table class="w-full min-w-[780px] text-left text-sm"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400 dark:bg-slate-800"><tr><th class="p-4">Request</th><th>Requested at</th><th>Method / account</th><th>Amount</th><th>Status</th><th>Reviewed at</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($withdrawals as $item)<tr class="hover:bg-slate-50 dark:hover:bg-slate-800/60"><td class="p-4 font-mono text-xs font-black text-indigo-600 dark:text-indigo-300">{{ $item->request_number }}</td><td class="whitespace-nowrap text-slate-600 dark:text-slate-300">{{ $item->created_at->format('d M Y') }}<span class="block text-[10px] text-slate-400">{{ $item->created_at->format('h:i A') }}</span></td><td class="text-slate-600 dark:text-slate-300"><b class="block text-xs text-slate-900 dark:text-white">{{ ucwords(str_replace('_', ' ', $item->payment_method)) }}</b><span class="block max-w-48 truncate text-[10px]">{{ $item->account_title }} · {{ $item->account_number }}</span></td><td class="whitespace-nowrap"><b class="block text-slate-950 dark:text-white">Rs {{ number_format($item->net_amount ?? $item->amount, 2) }}</b>@if((float) $item->fee_amount > 0)<span class="block text-[9px] text-slate-400">Requested {{ number_format($item->amount, 2) }} · Fee {{ number_format($item->fee_amount, 2) }}</span>@endif</td><td><span class="rounded-full px-2.5 py-1 text-[10px] font-black {{ $item->status === 'approved' ? 'bg-emerald-100 text-emerald-700' : ($item->status === 'rejected' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700') }}">{{ ucfirst($item->status) }}</span>@if($item->review_notes)<span class="mt-1 block max-w-40 text-[10px] text-slate-400">{{ $item->review_notes }}</span>@endif</td><td class="whitespace-nowrap text-slate-600 dark:text-slate-300">@if($item->reviewed_at){{ $item->reviewed_at->format('d M Y') }}<span class="block text-[10px] text-slate-400">{{ $item->reviewed_at->format('h:i A') }}</span>@else<span class="text-slate-400">—</span>@endif</td></tr>@empty<tr><td colspan="6" class="p-12 text-center"><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-indigo-50 text-xl text-indigo-600 dark:bg-slate-800">↗</span><b class="mt-3 block text-slate-900 dark:text-white">No withdrawal requests yet</b><span class="mt-1 block text-xs text-slate-400">Your requests will appear here.</span></td></tr>@endforelse</tbody></table></div>
                    @if($withdrawals->hasPages())<div class="border-t border-slate-100 p-4 dark:border-slate-800">{{ $withdrawals->links() }}</div>@endif
                </section>
            </div>
        </div>
    </div>
</x-app-layout>
