@php($portalAnnouncement = \App\Models\SiteSetting::customerPortalAnnouncement())
@if($portalAnnouncement['enabled'] && filled($portalAnnouncement['message']))
    <div x-data="{ open: true, dismiss() { this.open = false } }" x-init="$nextTick(() => $refs.dialogPanel.focus())" x-effect="document.body.style.overflow = open ? 'hidden' : ''" x-show="open" x-cloak x-transition.opacity @keydown.escape.window="dismiss()" class="fixed inset-0 z-[100] flex items-end justify-center sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="customer-announcement-title" aria-describedby="customer-announcement-message">
        <button type="button" @click="dismiss()" class="absolute inset-0 bg-white/75 backdrop-blur-sm dark:bg-slate-950/90" aria-label="Close announcement"></button>
        <section x-ref="dialogPanel" tabindex="-1" x-show="open" x-transition:enter="transition ease-out duration-300 delay-75" x-transition:enter-start="translate-y-8 scale-95 opacity-0" x-transition:enter-end="translate-y-0 scale-100 opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="translate-y-0 scale-100 opacity-100" x-transition:leave-end="translate-y-5 scale-95 opacity-0" class="relative mb-0 mt-14 w-full max-w-md rounded-t-[2rem] border-2 border-orange-300 bg-white px-5 pb-6 pt-20 text-center shadow-[0_24px_60px_-20px_rgba(71,58,25,.35)] outline-none motion-reduce:transform-none dark:border-orange-700 dark:bg-slate-900 sm:mb-4 sm:rounded-[2.25rem] sm:px-8 sm:pb-8 sm:pt-24">
            <div class="absolute left-1/2 top-0 h-28 w-28 -translate-x-1/2 -translate-y-[42%] rounded-[50%] border-2 border-orange-300 bg-white dark:border-orange-700 dark:bg-slate-900"><span class="absolute -bottom-1 -left-1 -right-1 h-[58%] bg-white dark:bg-slate-900"></span></div>
            <div class="absolute left-1/2 top-0 z-10 grid h-24 w-24 -translate-x-1/2 -translate-y-[42%] place-items-center rounded-full bg-slate-100 dark:bg-slate-800 sm:h-28 sm:w-28"><div class="relative -rotate-12 text-amber-400 drop-shadow-[0_6px_4px_rgba(180,113,0,.35)]"><svg class="h-10 w-10 sm:h-12 sm:w-12" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18 8a6 6 0 0 0-5-5.92V1a1 1 0 1 0-2 0v1.08A6 6 0 0 0 6 8c0 7-3 7-3 9a1 1 0 0 0 1 1h5a3 3 0 0 0 6 0h5a1 1 0 0 0 1-1c0-2-3-2-3-9Zm-6 12a1 1 0 0 1-1-1h2a1 1 0 0 1-1 1Z"/></svg></div></div>
            <button type="button" @click="dismiss()" class="absolute right-4 top-4 z-20 grid h-9 w-9 place-items-center rounded-full border border-slate-200 bg-slate-100 text-slate-600 shadow-sm transition hover:rotate-90 hover:border-orange-200 hover:bg-orange-50 hover:text-orange-600 focus:outline-none focus-visible:ring-2 focus-visible:ring-orange-500 focus-visible:ring-offset-2 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-300 sm:right-5 sm:top-5" aria-label="Close announcement"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true"><path stroke-linecap="round" d="M6 6l12 12M18 6 6 18"/></svg></button>
            <div class="relative z-10 mx-auto max-w-sm"><h2 id="customer-announcement-title" class="mx-auto mt-2 max-w-xs break-words text-lg font-extrabold leading-snug tracking-tight text-slate-900 dark:text-white sm:text-xl">{{ $portalAnnouncement['title'] }}</h2><div class="mx-auto mt-3 max-h-[24dvh] overflow-y-auto overscroll-contain px-1"><p id="customer-announcement-message" class="break-words whitespace-pre-line text-[13px] leading-5 text-slate-500 dark:text-slate-300">{{ $portalAnnouncement['message'] }}</p></div></div>
        </section>
    </div>
@endif
